name = "babyplaypenhouse"
compatibility_date = "2024-09-23"
pages_build_output_dir = "frontend/dist"

[[d1_databases]]
binding = "DB"
database_name = "baby-pen-house-db"
database_id = "8cd91517-09f6-4013-add1-bb1f3dca2d0c"
migrations_dir = "backend/drizzle"
