// ═══════════════════════════════════════════════════════════════
// PlayPen House — Consolidated API
// All routes, utilities, and middleware in a single entry point.
// Generated by merge-api.mjs on 2026-05-05
// ═══════════════════════════════════════════════════════════════

import { Hono } from "hono";
import { handle } from "hono/cloudflare-pages";
import { cors } from "hono/cors";
import { logger } from "hono/logger";
import { createClient } from "@libsql/client/web";
import { drizzle } from "drizzle-orm/libsql";
import { eq, count, like, or, and, isNotNull, desc, asc, sql, inArray, isNull } from "drizzle-orm";
import { sign } from "hono/jwt";
import type { LibSQLDatabase } from "drizzle-orm/libsql";
import * as schema from "../../backend/server/db/schema";

// ═══ TYPES ═══════════════════════════════════════════════════

type Bindings = {
  TURSO_URL: string;
  TURSO_AUTH_TOKEN: string;
  ADMIN_API_KEY: string;
  JWT_SECRET: string;
  GOOGLE_SCRIPT_URL: string;
  GMAIL_SENDER_EMAIL: string;
  ADMIN_NOTIFICATION_EMAIL: string;
  EMAIL_WEBHOOK_SECRET: string;
};

type Variables = {
  db: LibSQLDatabase<typeof schema>;
};

// ═══ HELPERS ═════════════════════════════════════════════════

const formatLinks = (c: any, path: string, id?: string) => {
  const baseUrl = new URL(c.req.url).origin + "/api/v1";
  const self = id ? `${baseUrl}${path}/${id}` : `${baseUrl}${path}`;
  return {
    self,
    collection: id ? `${baseUrl}${path}` : undefined,
  };
};

const createPaginatedResponse = (
  items: any[],
  total: number,
  page: number,
  limit: number,
  links: any
) => {
  const pages = Math.ceil(total / limit);
  return {
    items,
    pagination: {
      total,
      page,
      limit,
      pages,
      has_next: page < pages,
      has_prev: page > 1,
    },
    _links: links,
  };
};

// ═══ RATE LIMITER ════════════════════════════════════════════

// ── Rate Limiter (In-Memory) ────────────────────────────
// Simple per-IP rate limiter for Cloudflare Pages Functions.
// Uses a Map with TTL-based cleanup. Works for single-instance
// dev and low-traffic production. For high-traffic, upgrade to
// Cloudflare KV or Durable Objects.

interface RateEntry {
  count: number;
  resetAt: number;
}

const rateLimitMap = new Map<string, RateEntry>();

// Clean up stale entries every 60 seconds
const CLEANUP_INTERVAL = 60_000;
let lastCleanup = Date.now();

function cleanup() {
  const now = Date.now();
  if (now - lastCleanup < CLEANUP_INTERVAL) return;
  lastCleanup = now;
  for (const [key, entry] of rateLimitMap) {
    if (entry.resetAt < now) rateLimitMap.delete(key);
  }
}

/**
 * Check if a request should be rate-limited.
 * @param key   Unique identifier (e.g., IP + path)
 * @param limit Max requests allowed in the window
 * @param windowMs  Time window in milliseconds
 * @returns { limited: boolean, remaining: number, resetAt: number }
 */
export function checkRateLimit(
  key: string,
  limit: number = 5,
  windowMs: number = 60_000
): { limited: boolean; remaining: number; resetAt: number } {
  cleanup();

  const now = Date.now();
  const entry = rateLimitMap.get(key);

  if (!entry || entry.resetAt < now) {
    // New window
    rateLimitMap.set(key, { count: 1, resetAt: now + windowMs });
    return { limited: false, remaining: limit - 1, resetAt: now + windowMs };
  }

  entry.count++;
  if (entry.count > limit) {
    return { limited: true, remaining: 0, resetAt: entry.resetAt };
  }

  return { limited: false, remaining: limit - entry.count, resetAt: entry.resetAt };
}


// ═══ EMAIL UTILITY ═══════════════════════════════════════════

// ── Email Utility (Google Apps Script Webhook) ─────────────
// Sends emails via a deployed Google Apps Script that uses
// GmailApp.sendEmail() — fully compatible with Cloudflare Workers/Pages.
//
// Setup:
// 1. Create a Google Apps Script at https://script.google.com
// 2. Paste the doPost handler (see below)
// 3. Deploy as Web App → "Anyone" can access
// 4. Copy the URL → put in GOOGLE_SCRIPT_URL env var

/**
 * Google Apps Script code to deploy:
 * 
 * function doPost(e) {
 *   var data = JSON.parse(e.postData.contents);
 *   
 *   var secret = PropertiesService.getScriptProperties().getProperty('WEBHOOK_SECRET');
 *   if (secret && data.secret !== secret) {
 *     return ContentService.createTextOutput(JSON.stringify({ error: "Unauthorized" }))
 *       .setMimeType(ContentService.MimeType.JSON);
 *   }
 *
 *   GmailApp.sendEmail(data.to, data.subject, data.text, {
 *     htmlBody: data.html,
 *     name: data.senderName || "PlayPen House"
 *   });
 *   return ContentService.createTextOutput(JSON.stringify({ success: true }))
 *     .setMimeType(ContentService.MimeType.JSON);
 * }
 */

export interface EmailPayload {
  to: string;
  subject: string;
  text: string;
  html?: string;
  senderName?: string;
}

/**
 * Send an email via the Google Apps Script webhook.
 * Returns true on success, false on failure (never throws).
 */
export async function sendEmail(
  scriptUrl: string,
  webhookSecret: string | undefined,
  payload: EmailPayload
): Promise<boolean> {
  if (!scriptUrl) {
    console.warn("[EMAIL] GOOGLE_SCRIPT_URL not set — email skipped:", payload.subject);
    return false;
  }

  try {
    const res = await fetch(scriptUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        secret: webhookSecret,
        to: payload.to,
        subject: payload.subject,
        text: payload.text,
        html: payload.html || payload.text,
        senderName: payload.senderName || "PlayPen House",
      }),
    });

    if (!res.ok) {
      console.error("[EMAIL] Script returned non-OK:", res.status, await res.text());
      return false;
    }

    console.log("[EMAIL] Sent successfully to:", payload.to, "subject:", payload.subject);
    return true;
  } catch (err: any) {
    console.error("[EMAIL] Failed to send:", err.message);
    return false;
  }
}

// ── Email Templates ──────────────────────────────────────

export function otpEmailHtml(code: string, username: string): string {
  return `
    <div style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 480px; margin: 0 auto; padding: 32px; background: #fff; border-radius: 16px; border: 1px solid #eee;">
      <div style="text-align: center; margin-bottom: 24px;">
        <h1 style="color: #1a1a2e; font-size: 24px; margin: 0;">🏠 PlayPen House</h1>
        <p style="color: #888; font-size: 14px; margin: 8px 0 0;">Email Verification</p>
      </div>
      <p style="color: #333; font-size: 15px; line-height: 1.6;">Hi <strong>${username}</strong>,</p>
      <p style="color: #333; font-size: 15px; line-height: 1.6;">Your verification code is:</p>
      <div style="text-align: center; margin: 24px 0;">
        <div style="display: inline-block; background: linear-gradient(135deg, #1a1a2e, #16213e); color: #fff; font-size: 32px; font-weight: 900; letter-spacing: 8px; padding: 16px 32px; border-radius: 12px;">
          ${code}
        </div>
      </div>
      <p style="color: #888; font-size: 13px; text-align: center;">This code expires in <strong>10 minutes</strong>.</p>
      <hr style="border: none; border-top: 1px solid #eee; margin: 24px 0;" />
      <p style="color: #aaa; font-size: 11px; text-align: center;">If you didn't request this, please ignore this email.</p>
    </div>
  `;
}

export function passwordResetEmailHtml(code: string, email: string): string {
  return `
    <div style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 480px; margin: 0 auto; padding: 32px; background: #fff; border-radius: 16px; border: 1px solid #eee;">
      <div style="text-align: center; margin-bottom: 24px;">
        <h1 style="color: #1a1a2e; font-size: 24px; margin: 0;">🏠 PlayPen House</h1>
        <p style="color: #888; font-size: 14px; margin: 8px 0 0;">Password Reset</p>
      </div>
      <p style="color: #333; font-size: 15px; line-height: 1.6;">A password reset was requested for <strong>${email}</strong>.</p>
      <p style="color: #333; font-size: 15px; line-height: 1.6;">Your reset code is:</p>
      <div style="text-align: center; margin: 24px 0;">
        <div style="display: inline-block; background: linear-gradient(135deg, #e74c3c, #c0392b); color: #fff; font-size: 32px; font-weight: 900; letter-spacing: 8px; padding: 16px 32px; border-radius: 12px;">
          ${code}
        </div>
      </div>
      <p style="color: #888; font-size: 13px; text-align: center;">This code expires in <strong>10 minutes</strong>.</p>
      <hr style="border: none; border-top: 1px solid #eee; margin: 24px 0;" />
      <p style="color: #aaa; font-size: 11px; text-align: center;">If you didn't request this, please ignore this email.</p>
    </div>
  `;
}

export function orderConfirmationEmailHtml(
  invoiceId: string,
  customerName: string,
  totalAmount: number,
  items: { name: string; quantity: number; price: number }[]
): string {
  const itemRows = items
    .map(
      (item) => `
      <tr>
        <td style="padding: 8px 12px; border-bottom: 1px solid #f0f0f0; font-size: 14px;">${item.name}</td>
        <td style="padding: 8px 12px; border-bottom: 1px solid #f0f0f0; font-size: 14px; text-align: center;">${item.quantity}</td>
        <td style="padding: 8px 12px; border-bottom: 1px solid #f0f0f0; font-size: 14px; text-align: right;">$${item.price.toFixed(2)}</td>
      </tr>`
    )
    .join("");

  return `
    <div style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 520px; margin: 0 auto; padding: 32px; background: #fff; border-radius: 16px; border: 1px solid #eee;">
      <div style="text-align: center; margin-bottom: 24px;">
        <h1 style="color: #1a1a2e; font-size: 24px; margin: 0;">🏠 PlayPen House</h1>
        <p style="color: #22c55e; font-size: 14px; font-weight: 700; margin: 8px 0 0;">✅ Order Confirmed</p>
      </div>
      <p style="color: #333; font-size: 15px;">Hi <strong>${customerName}</strong>,</p>
      <p style="color: #333; font-size: 15px;">Your order <strong>${invoiceId}</strong> has been placed successfully and is awaiting approval.</p>
      <table style="width: 100%; border-collapse: collapse; margin: 16px 0;">
        <thead>
          <tr style="background: #f8f9fa;">
            <th style="padding: 8px 12px; text-align: left; font-size: 12px; text-transform: uppercase; color: #888;">Item</th>
            <th style="padding: 8px 12px; text-align: center; font-size: 12px; text-transform: uppercase; color: #888;">Qty</th>
            <th style="padding: 8px 12px; text-align: right; font-size: 12px; text-transform: uppercase; color: #888;">Price</th>
          </tr>
        </thead>
        <tbody>${itemRows}</tbody>
      </table>
      <div style="text-align: right; margin-top: 12px; font-size: 18px; font-weight: 900; color: #1a1a2e;">
        Total: $${totalAmount.toFixed(2)}
      </div>
      <hr style="border: none; border-top: 1px solid #eee; margin: 24px 0;" />
      <p style="color: #aaa; font-size: 11px; text-align: center;">Thank you for shopping with PlayPen House!</p>
    </div>
  `;
}

export function adminNewOrderEmailHtml(
  invoiceId: string,
  customerName: string,
  totalAmount: number,
  itemCount: number
): string {
  return `
    <div style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 480px; margin: 0 auto; padding: 32px; background: #fff; border-radius: 16px; border: 2px solid #f59e0b;">
      <div style="text-align: center; margin-bottom: 24px;">
        <h1 style="color: #1a1a2e; font-size: 24px; margin: 0;">🏠 PlayPen House — Admin</h1>
        <p style="color: #f59e0b; font-size: 14px; font-weight: 700; margin: 8px 0 0;">🔔 New Order Awaiting Approval</p>
      </div>
      <table style="width: 100%; font-size: 15px; color: #333;">
        <tr><td style="padding: 6px 0; font-weight: 700;">Invoice</td><td>${invoiceId}</td></tr>
        <tr><td style="padding: 6px 0; font-weight: 700;">Customer</td><td>${customerName}</td></tr>
        <tr><td style="padding: 6px 0; font-weight: 700;">Items</td><td>${itemCount} item(s)</td></tr>
        <tr><td style="padding: 6px 0; font-weight: 700;">Total</td><td style="font-size: 18px; font-weight: 900; color: #22c55e;">$${totalAmount.toFixed(2)}</td></tr>
      </table>
      <div style="text-align: center; margin-top: 24px;">
        <p style="color: #888; font-size: 13px;">Please log in to the Admin Panel to approve or reject this order.</p>
      </div>
    </div>
  `;
}

export function orderStatusUpdateEmailHtml(
  invoiceId: string,
  customerName: string,
  newStatus: string,
  message?: string
): string {
  const statusColors: Record<string, string> = {
    Processing: "#3b82f6",
    Shipped: "#8b5cf6",
    "Out for Delivery": "#f59e0b",
    Delivered: "#22c55e",
    Cancelled: "#ef4444",
  };
  const color = statusColors[newStatus] || "#6b7280";

  return `
    <div style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 480px; margin: 0 auto; padding: 32px; background: #fff; border-radius: 16px; border: 1px solid #eee;">
      <div style="text-align: center; margin-bottom: 24px;">
        <h1 style="color: #1a1a2e; font-size: 24px; margin: 0;">🏠 PlayPen House</h1>
        <p style="color: #888; font-size: 14px; margin: 8px 0 0;">Order Update</p>
      </div>
      <p style="color: #333; font-size: 15px;">Hi <strong>${customerName}</strong>,</p>
      <p style="color: #333; font-size: 15px;">Your order <strong>${invoiceId}</strong> has been updated:</p>
      <div style="text-align: center; margin: 24px 0;">
        <span style="display: inline-block; background: ${color}; color: #fff; font-size: 16px; font-weight: 700; padding: 10px 28px; border-radius: 999px;">
          ${newStatus}
        </span>
      </div>
      ${message ? `<p style="color: #555; font-size: 14px; text-align: center; font-style: italic;">"${message}"</p>` : ""}
      <hr style="border: none; border-top: 1px solid #eee; margin: 24px 0;" />
      <p style="color: #aaa; font-size: 11px; text-align: center;">Thank you for shopping with PlayPen House!</p>
    </div>
  `;
}


// ═══ APP SETUP ═══════════════════════════════════════════════

const app = new Hono<{ Bindings: Bindings; Variables: Variables }>();

// API Tracking (Dev only persistence)
let globalRequestCount = 0;
const apiStartTime = Date.now();


app.use("*", logger());
app.use("*", cors());

// Request Counter Middleware
app.use("*", async (c, next) => {
  globalRequestCount++;
  await next();
});


// DB Middleware
app.use("*", async (c, next) => {
  const url = c.env.TURSO_URL;
  const authToken = c.env.TURSO_AUTH_TOKEN;

  if (!url || url.includes("your-db-url")) {
    if (c.req.path === "/api/health" || c.req.path === "/api/v1/health") {
      return await next();
    }
    return c.json({
      error: "Database Configuration Error",
      message: "TURSO_URL is missing or using placeholder."
    }, 503);
  }

  try {
    const client = createClient({ url, authToken });
    c.set("db", drizzle(client, { schema }));
    await next();
  } catch (error: any) {
    console.error("DB Connection Error:", error);
    return c.json({
      error: "Service Unavailable",
      message: "Could not connect to the database."
    }, 503);
  }
});

// Error Handling
app.onError((err, c) => {
  console.error("API Error:", err);

  if (err.message.startsWith("VAL:")) {
    return c.json({
      error: "ValidationError",
      message: err.message.replace("VAL:", "").trim(),
      timestamp: new Date().toISOString(),
      path: c.req.path
    }, 422);
  }

  if (err.message.includes("not found")) {
    return c.json({
      error: "NotFound",
      message: err.message,
      timestamp: new Date().toISOString(),
      path: c.req.path
    }, 404);
  }

  return c.json({
    error: "InternalServerError",
    message: "An unexpected error occurred.",
    details: process.env.NODE_ENV === 'development' ? err.message : undefined,
    timestamp: new Date().toISOString(),
    path: c.req.path
  }, 500);
});

// ─── HEALTH CHECK ─────────────────────────────────────────
app.get("/api/health", (c) => c.json({ status: "ok", version: "v1" }));

// ═══ V1 ROUTES ══════════════════════════════════════════════

const v1 = new Hono<{ Bindings: Bindings; Variables: Variables }>();

// ── STATS ──────────────────────────────────────────────────
v1.get("/stats", (c) => {
  const uptimeMs = Date.now() - apiStartTime;
  const uptimeSec = Math.floor(uptimeMs / 1000);
  const rpm = uptimeSec > 0 ? (globalRequestCount / (uptimeSec / 60)).toFixed(2) : "0.00";

  return c.json({
    total_requests: globalRequestCount,
    uptime_seconds: uptimeSec,
    requests_per_minute: rpm,
    average_latency_ms: "Calculated by client",
    current_time: new Date().toISOString()
  });
});

// ── BULK HOME ──────────────────────────────────────────────
v1.get("/bulk/home", async (c) => {
  const db = c.get("db");
  try {
    const [
      bannersHero,
      bannersMid1,
      bannersMid2,
      categories,
      trendingProducts,
      newArrivals,
      specialOffers,
      bestSelling,
      notifications
    ] = await Promise.all([
      db.query.banners.findMany({
        where: (b: any, { eq }: any) => eq(b.position, 'hero'),
        orderBy: (b: any, { asc }: any) => [asc(b.order)]
      }),
      db.query.banners.findMany({
        where: (b: any, { eq }: any) => eq(b.position, 'mid-1'),
        orderBy: (b: any, { asc }: any) => [asc(b.order)]
      }),
      db.query.banners.findMany({
        where: (b: any, { eq }: any) => eq(b.position, 'mid-2'),
        orderBy: (b: any, { asc }: any) => [asc(b.order)]
      }),
      db.query.categories.findMany({
        where: (cat: any, { eq }: any) => eq(cat.isActive, 1)
      }),
      db.query.products.findMany({
        limit: 10,
        orderBy: (p: any, { desc }: any) => [desc(p.rating)]
      }),
      db.query.products.findMany({
        limit: 8,
        where: (p: any, { like }: any) => like(p.tags, '%"new-arrival"%'),
        orderBy: (p: any, { desc }: any) => [desc(p.createdAt)]
      }),
      db.query.products.findMany({
        limit: 4,
        where: (p: any, { and, isNotNull, like }: any) => and(isNotNull(p.salePrice), like(p.tags, '%"special-offer"%'))
      }),
      db.query.products.findMany({
        limit: 8,
        where: (p: any, { like }: any) => like(p.tags, '%"best-selling"%'),
        orderBy: (p: any, { desc }: any) => [desc(p.soldCount)]
      }),
      db.query.notifications.findMany({
        where: (n: any, { isNull }: any) => isNull(n.userId),
        limit: 5,
        orderBy: (n: any, { desc }: any) => [desc(n.createdAt)]
      })
    ]);

    return c.json({
      banners: {
        hero: bannersHero,
        mid1: bannersMid1,
        mid2: bannersMid2
      },
      categories: { items: categories },
      products: {
        trending: { items: trendingProducts },
        newArrivals: { items: newArrivals },
        specialOffers: { items: specialOffers },
        bestSelling: { items: bestSelling }
      },
      notifications: { items: notifications },
      timestamp: new Date().toISOString()
    });
  } catch (error: any) {
    console.error("Bulk fetch error:", error.message);
    return c.json({ error: "Bulk fetch failed", details: error.message }, 500);
  }
});


// Auth Middleware for V1 (Destructive operations only)
v1.use("*", async (c, next) => {
  const method = c.req.method;
  if (method === 'GET') return await next();

  const path = c.req.path;
  const publicPaths = ["/api/v1/auth/", "/api/v1/orders", "/api/v1/reviews", "/api/v1/returns", "/api/v1/addresses", "/api/v1/users/", "/api/v1/coupons/validate"];
  const isPublic = publicPaths.some(p => path.startsWith(p));
  if (isPublic) return await next();

  const authHeader = c.req.header("Authorization");
  const apiKey = c.env.ADMIN_API_KEY;

  if (!apiKey || authHeader !== `Bearer ${apiKey}`) {
    return c.json({
      error: "Unauthorized",
      message: "Invalid or missing API key"
    }, 401);
  }
  await next();
});

// ── BANNERS ────────────────────────────────────────────────

const bannersRouter = new Hono<{ Bindings: Bindings; Variables: Variables }>();

bannersRouter.get("/", async (c) => {
  try {
    const position = c.req.query("position");
    const db = c.get("db");

    const rows = await db.query.banners.findMany({
      where: position ? (b: any, { eq }: any) => eq(b.position, position) : undefined,
      orderBy: (b: any, { asc }: any) => [asc(b.order)],
    });

    return c.json({
      items: rows.map((r: any) => ({
        ...r,
        _links: formatLinks(c, "/banners", r.id)
      })),
      _links: formatLinks(c, "/banners")
    });
  } catch (error: any) {
    console.error("Fetch banners error:", error.message);
    return c.json({ items: [], _links: formatLinks(c, "/banners") });
  }
});

bannersRouter.post("/", async (c) => {
  const db = c.get("db");
  const body = await c.req.json().catch(() => null);

  if (!body?.image || !body?.position) {
    throw new Error("VAL: Image and position are required fields.");
  }

  const id = crypto.randomUUID();
  await db.insert(schema.banners).values({
    id,
    image: body.image,
    link: body.link || null,
    position: body.position,
    order: Number(body.order) || 0,
    isActive: 1,
  });

  return c.json({
    id,
    message: "Banner created successfully",
    _links: formatLinks(c, "/banners", id)
  }, 201);
});

bannersRouter.patch("/:id", async (c) => {
  const id = c.req.param("id");
  const db = c.get("db");
  const body = await c.req.json();

  const [existing] = await db.select().from(schema.banners).where(eq(schema.banners.id, id));
  if (!existing) throw new Error(`Banner with ID ${id} not found`);

  await db.update(schema.banners)
    .set({
      image: body.image ?? existing.image,
      link: body.link ?? existing.link,
      position: body.position ?? existing.position,
      order: body.order !== undefined ? Number(body.order) : existing.order,
      isActive: body.isActive !== undefined ? (body.isActive ? 1 : 0) : existing.isActive,
    })
    .where(eq(schema.banners.id, id));

  return c.json({
    message: "Banner updated successfully",
    _links: formatLinks(c, "/banners", id)
  });
});

bannersRouter.delete("/:id", async (c) => {
  const id = c.req.param("id");
  const db = c.get("db");

  await db.delete(schema.banners).where(eq(schema.banners.id, id));
  return c.body(null, 204);
});

// ── CATEGORIES ─────────────────────────────────────────────

const categoriesRouter = new Hono<{ Bindings: Bindings; Variables: Variables }>();

categoriesRouter.get("/", async (c) => {
  try {
    const db = c.get("db");
    const featured = c.req.query("featured") === "true";
    const showAll = c.req.query("all") === "true";

    const rows = await db.query.categories.findMany({
      where: (cat: any, { eq, and }: any) => {
        if (showAll && !featured) return undefined;

        const filters = [];
        if (!showAll) filters.push(eq(cat.isActive, 1));
        if (featured) filters.push(eq(cat.isFeatured, 1));

        return filters.length > 0 ? and(...filters) : undefined;
      },
    });

    return c.json({
      items: rows.map((r: any) => ({
        ...r,
        _links: formatLinks(c, "/categories", r.id)
      })),
      _links: formatLinks(c, "/categories")
    });
  } catch (error: any) {
    console.error("Fetch categories error:", error.message);
    return c.json({ items: [], _links: formatLinks(c, "/categories") });
  }
});

categoriesRouter.post("/", async (c) => {
  const db = c.get("db");
  const body = await c.req.json().catch(() => null);

  if (!body?.name) {
    throw new Error("VAL: Category name is required.");
  }

  const id = crypto.randomUUID();
  const slug = body.name.toLowerCase().replace(/ /g, "-") + "-" + id.slice(0, 5);

  await db.insert(schema.categories).values({
    id,
    name: body.name,
    slug: body.slug || slug,
    parentId: body.parentId || null,
    image: body.image || null,
    isFeatured: body.isFeatured ? 1 : 0,
    isActive: body.isActive !== undefined ? (body.isActive ? 1 : 0) : 1,
  });

  return c.json({
    id,
    message: "Category created successfully",
    _links: formatLinks(c, "/categories", id)
  }, 201);
});

categoriesRouter.patch("/:id", async (c) => {
  const id = c.req.param("id");
  const db = c.get("db");
  const body = await c.req.json();

  const [existing] = await db.select().from(schema.categories).where(eq(schema.categories.id, id));
  if (!existing) throw new Error(`Category with ID ${id} not found`);

  await db.update(schema.categories)
    .set({
      name: body.name ?? existing.name,
      slug: body.slug ?? existing.slug,
      parentId: body.parentId !== undefined ? body.parentId : existing.parentId,
      image: body.image ?? existing.image,
      isFeatured: body.isFeatured !== undefined ? (body.isFeatured ? 1 : 0) : existing.isFeatured,
      isActive: body.isActive !== undefined ? (body.isActive ? 1 : 0) : existing.isActive,
    })
    .where(eq(schema.categories.id, id));

  return c.json({
    message: "Category updated successfully",
    _links: formatLinks(c, "/categories", id)
  });
});

categoriesRouter.delete("/:id", async (c) => {
  const id = c.req.param("id");
  const db = c.get("db");

  await db.delete(schema.categories).where(eq(schema.categories.id, id));
  return c.body(null, 204);
});

// ── PRODUCTS ───────────────────────────────────────────────

const productsRouter = new Hono<{ Bindings: Bindings; Variables: Variables }>();

productsRouter.get("/", async (c) => {
  try {
    const db = c.get("db");
    const page = Math.max(1, Number(c.req.query("page") || 1));
    const limit = Math.min(100, Math.max(1, Number(c.req.query("limit") || 12)));
    const offset = (page - 1) * limit;

    const { category, tag, sort, q, hasOffer } = c.req.query();

    // Base query
    let conditions = [];
    if (category) {
      conditions.push(eq(schema.products.categoryId, category));
    }
    if (q) {
      conditions.push(
        or(
          like(schema.products.title, `%${q}%`),
          like(schema.products.brand, `%${q}%`)
        )
      );
    }
    if (tag) {
      conditions.push(like(schema.products.tags, `%"${tag}"%`));
    }
    if (hasOffer === 'true') {
      conditions.push(isNotNull(schema.products.salePrice));
    }

    const whereClause = conditions.length > 0 ? and(...conditions) : undefined;

    const [totalRes] = await db.select({ count: count() }).from(schema.products).where(whereClause);
    const total = totalRes.count;

    const rows = await db.query.products.findMany({
      where: whereClause,
      limit,
      offset,
      orderBy: (p: any, { desc, asc }: any) => {
        if (sort === "newest") return [desc(p.createdAt)];
        if (sort === "price-low") return [asc(p.price)];
        if (sort === "price-high") return [desc(p.price)];
        if (sort === "best-selling") return [desc(p.soldCount)];
        if (sort === "trending") return [desc(p.rating)];
        return [desc(p.createdAt)]; // default to newest
      }
    });

    return c.json(createPaginatedResponse(
      rows.map((r: any) => ({ ...r, _links: formatLinks(c, "/products", r.id) })),
      total,
      page,
      limit,
      formatLinks(c, "/products")
    ));
  } catch (error: any) {
    console.error("Fetch products error:", error.message);
    return c.json(createPaginatedResponse([], 0, 1, 12, formatLinks(c, "/products")));
  }
});

productsRouter.get("/search", async (c) => {
  try {
    const q = c.req.query("q") ?? "";
    const db = c.get("db");

    const rows = await db.query.products.findMany({
      where: (p: any, { like, or }: any) => or(
        like(p.title, `%${q}%`),
        like(p.brand, `%${q}%`)
      ),
      limit: 10,
    });

    return c.json({
      items: rows.map((r: any) => ({ ...r, _links: formatLinks(c, "/products", r.id) })),
      query: q,
      _links: formatLinks(c, "/products/search")
    });
  } catch (error: any) {
    console.error("Search products error:", error.message);
    return c.json({ items: [], query: c.req.query("q") ?? "", _links: formatLinks(c, "/products/search") });
  }
});

productsRouter.get("/by-slug/:slug", async (c) => {
  const slug = c.req.param("slug");
  const db = c.get("db");

  const [product] = await db.select().from(schema.products).where(eq(schema.products.slug, slug));
  if (!product) {
    return c.json({ error: "Product not found" }, 404);
  }

  return c.json({
    ...product,
    _links: formatLinks(c, "/products", product.id)
  });
});

productsRouter.get("/:id", async (c) => {
  const id = c.req.param("id");
  const db = c.get("db");

  const [product] = await db.select().from(schema.products).where(eq(schema.products.id, id));
  if (!product) throw new Error(`Product with ID ${id} not found`);

  return c.json({
    ...product,
    _links: formatLinks(c, "/products", id)
  });
});

productsRouter.post("/", async (c) => {
  const db = c.get("db");
  const body = await c.req.json().catch(() => null);

  if (!body?.title || !body?.price) {
    throw new Error("VAL: Title and price are required fields.");
  }

  const id = crypto.randomUUID();
  const slug = body.title.toLowerCase().replace(/ /g, "-") + "-" + id.slice(0, 5);

  await db.insert(schema.products).values({
    id,
    title: body.title,
    slug: body.slug || slug,
    categoryId: body.categoryId || null,
    brand: body.brand || "Generic",
    price: Number(body.price),
    salePrice: body.salePrice ? Number(body.salePrice) : null,
    stock: Number(body.stock) || 0,
    images: body.images ? (typeof body.images === 'string' ? body.images : JSON.stringify(body.images)) : "[]",
    tags: body.tags ? (typeof body.tags === 'string' ? body.tags : JSON.stringify(body.tags)) : "[]",
    rating: 0,
    reviewCount: 0,
    soldCount: body.soldCount || 0,
    isActive: 1,
    createdAt: new Date(),
  });

  return c.json({
    id,
    message: "Product created successfully",
    _links: formatLinks(c, "/products", id)
  }, 201);
});

productsRouter.patch("/:id", async (c) => {
  const id = c.req.param("id");
  const db = c.get("db");
  const body = await c.req.json();

  const [existing] = await db.select().from(schema.products).where(eq(schema.products.id, id));
  if (!existing) throw new Error(`Product with ID ${id} not found`);

  await db.update(schema.products)
    .set({
      title: body.title ?? existing.title,
      slug: body.slug ?? existing.slug,
      categoryId: body.categoryId ?? existing.categoryId,
      brand: body.brand ?? existing.brand,
      price: body.price !== undefined ? Number(body.price) : existing.price,
      salePrice: body.salePrice !== undefined ? (body.salePrice ? Number(body.salePrice) : null) : existing.salePrice,
      stock: body.stock !== undefined ? Number(body.stock) : existing.stock,
      images: body.images !== undefined ? (typeof body.images === 'string' ? body.images : JSON.stringify(body.images)) : existing.images,
      tags: body.tags !== undefined ? (typeof body.tags === 'string' ? body.tags : JSON.stringify(body.tags)) : existing.tags,
      soldCount: body.soldCount !== undefined ? Number(body.soldCount) : existing.soldCount,
      isActive: body.isActive !== undefined ? (body.isActive ? 1 : 0) : existing.isActive,
    })
    .where(eq(schema.products.id, id));

  return c.json({
    message: "Product updated successfully",
    _links: formatLinks(c, "/products", id)
  });
});

productsRouter.delete("/:id", async (c) => {
  const id = c.req.param("id");
  const db = c.get("db");

  await db.delete(schema.products).where(eq(schema.products.id, id));
  return c.body(null, 204);
});

// ── ORDERS ─────────────────────────────────────────────────

const ordersRouter = new Hono<{ Bindings: Bindings; Variables: Variables }>();

ordersRouter.get("/", async (c) => {
  try {
    const db = c.get("db");
    const customerName = c.req.query("customerName");

    const rows = await db.query.orders.findMany({
      where: customerName ? (o: any, { eq }: any) => eq(o.customerName, customerName) : undefined,
      orderBy: (o: any, { desc }: any) => [desc(o.createdAt)],
    });

    return c.json({
      items: rows.map((r: any) => ({ ...r, _links: formatLinks(c, "/orders", r.id) })),
      _links: formatLinks(c, "/orders")
    });
  } catch (error: any) {
    console.error("Fetch orders error:", error.message);
    return c.json({ items: [], _links: formatLinks(c, "/orders") });
  }
});

ordersRouter.get("/:id", async (c) => {
  const id = c.req.param("id");
  const db = c.get("db");

  const [order] = await db.select().from(schema.orders).where(eq(schema.orders.id, id));
  if (!order) throw new Error(`Order with ID ${id} not found`);

  const orderItemsList = await db.select().from(schema.orderItems).where(eq(schema.orderItems.orderId, id));

  // Fetch product names for the items
  const itemsWithProduct = await Promise.all(orderItemsList.map(async (item: any) => {
    const [product] = await db.select().from(schema.products).where(eq(schema.products.id, item.productId));
    return {
      ...item,
      productName: product ? product.title : 'Deleted Product',
      productImage: product ? ((() => {
        try {
          const imgs = JSON.parse(product.images || '[]');
          return imgs[0] || null;
        } catch { return null; }
      })()) : null
    };
  }));

  const trackings = await db.select().from(schema.trackings).where(eq(schema.trackings.orderId, id));

  return c.json({
    ...order,
    items: itemsWithProduct,
    trackings: trackings.sort((a: any, b: any) => new Date(b.createdAt!).getTime() - new Date(a.createdAt!).getTime()), // newest first
    _links: formatLinks(c, "/orders", id)
  });
});

ordersRouter.post("/", async (c) => {
  const db = c.get("db");
  const body = await c.req.json().catch(() => null);

  if (!body?.customerName || !body?.shippingAddress || !body?.items || !body.items.length) {
    throw new Error("VAL: Customer name, shipping address, and items are required fields.");
  }

  // ── Stock Validation ──────────────────────────────────
  for (const item of body.items) {
    const [product] = await db.select().from(schema.products).where(eq(schema.products.id, item.productId));
    if (!product) {
      throw new Error(`VAL: Product "${item.productName || item.productId}" not found.`);
    }
    const availableStock = (product.stock ?? 0) - (product.soldCount ?? 0);
    if (availableStock < item.quantity) {
      throw new Error(
        `VAL: Insufficient stock for "${product.title}". Available: ${availableStock}, Requested: ${item.quantity}.`
      );
    }
  }

  // ── Increment Sold Count ────────────────
  for (const item of body.items) {
    const [product] = await db.select().from(schema.products).where(eq(schema.products.id, item.productId));
    await db.update(schema.products)
      .set({
        soldCount: (product!.soldCount ?? 0) + item.quantity
      })
      .where(eq(schema.products.id, item.productId));
  }

  const id = crypto.randomUUID();

  const d = new Date();
  const dd = String(d.getDate()).padStart(2, '0');
  const mm = String(d.getMonth() + 1).padStart(2, '0');
  const yyyy = d.getFullYear();

  const existingOrders = await db.select().from(schema.orders);
  const orderNum = String(existingOrders.length + 1).padStart(3, '0');
  const invoiceId = `${dd}${mm}${yyyy}-${orderNum}`;

  const totalAmount = body.items.reduce((sum: number, item: any) => sum + (item.price * item.quantity), 0);

  await db.insert(schema.orders).values({
    id,
    invoiceId,
    customerName: body.customerName,
    customerEmail: body.customerEmail || null,
    customerPhone: body.customerPhone || "N/A",
    shippingAddress: body.shippingAddress,
    totalAmount,
    status: body.paymentMethod && body.paymentMethod !== "cod" && body.paymentMethod !== "wallet" ? "Pending Verification" : "Pending",
    paymentMethod: body.paymentMethod || "cod",
    paymentPhone: body.paymentPhone || null,
    paymentTrxId: body.paymentTrxId || null,
    createdAt: new Date(),
  });

  for (const item of body.items) {
    await db.insert(schema.orderItems).values({
      id: crypto.randomUUID(),
      orderId: id,
      productId: item.productId,
      quantity: item.quantity,
      price: item.price,
    });
  }

  await db.insert(schema.trackings).values({
    id: crypto.randomUUID(),
    orderId: id,
    status: "Order Placed",
    message: "Your order has been placed successfully and is awaiting approval.",
    createdAt: new Date(),
  });

  // ── Email: Customer Confirmation ──────────────────
  if (body.customerEmail && c.env.GOOGLE_SCRIPT_URL) {
    const itemSummary = body.items.map((item: any) => ({
      name: item.productName || item.productId,
      quantity: item.quantity,
      price: item.price,
    }));

    sendEmail(c.env.GOOGLE_SCRIPT_URL, c.env.EMAIL_WEBHOOK_SECRET, {
      to: body.customerEmail,
      subject: `PlayPen House — Order Confirmed (${invoiceId})`,
      text: `Hi ${body.customerName}, your order ${invoiceId} has been placed! Total: $${totalAmount.toFixed(2)}`,
      html: orderConfirmationEmailHtml(invoiceId, body.customerName, totalAmount, itemSummary),
    }).catch(() => { }); // fire and forget
  }

  // ── Email: Admin Notification ─────────────────────
  const adminEmail = c.env.ADMIN_NOTIFICATION_EMAIL;
  if (adminEmail && c.env.GOOGLE_SCRIPT_URL) {
    sendEmail(c.env.GOOGLE_SCRIPT_URL, c.env.EMAIL_WEBHOOK_SECRET, {
      to: adminEmail,
      subject: `🔔 New Order Awaiting Approval — ${invoiceId}`,
      text: `New order from ${body.customerName}. Invoice: ${invoiceId}. Total: $${totalAmount.toFixed(2)}. ${body.items.length} item(s). Please log in to approve.`,
      html: adminNewOrderEmailHtml(invoiceId, body.customerName, totalAmount, body.items.length),
    }).catch(() => { }); // fire and forget
  }

  return c.json({
    id,
    invoiceId,
    message: "Order placed successfully",
    _links: formatLinks(c, "/orders", id)
  }, 201);
});

ordersRouter.patch("/:id/status", async (c) => {
  const id = c.req.param("id");
  const db = c.get("db");
  const body = await c.req.json();

  const [existing] = await db.select().from(schema.orders).where(eq(schema.orders.id, id));
  if (!existing) throw new Error(`Order with ID ${id} not found`);

  const newStatus = body.status ?? existing.status;

  await db.update(schema.orders)
    .set({
      status: newStatus,
    })
    .where(eq(schema.orders.id, id));

  // ── Notification: Notify customer about status change ────
  try {
    let notifyUserId = null;
    if (existing.customerEmail) {
      const [usr] = await db.select().from(schema.users).where(eq(schema.users.email, existing.customerEmail));
      if (usr) notifyUserId = usr.id;
    }
    await db.insert(schema.notifications).values({
      id: crypto.randomUUID(),
      userId: notifyUserId,
      title: `Order Status Updated — ${existing.invoiceId}`,
      message: `Your order ${existing.invoiceId} status is now: ${newStatus}.`,
      type: "order_status",
      isRead: 0,
      createdAt: new Date().toISOString(),
    });
  } catch (err) {
    console.error("Failed to insert notification:", err);
  }

  // ── Email: Notify customer about status change ────
  if (existing.customerEmail && c.env.GOOGLE_SCRIPT_URL && newStatus !== existing.status) {
    sendEmail(c.env.GOOGLE_SCRIPT_URL, c.env.EMAIL_WEBHOOK_SECRET, {
      to: existing.customerEmail,
      subject: `PlayPen House — Order ${existing.invoiceId} is now "${newStatus}"`,
      text: `Hi ${existing.customerName}, your order ${existing.invoiceId} status has been updated to: ${newStatus}.`,
      html: orderStatusUpdateEmailHtml(
        existing.invoiceId!,
        existing.customerName,
        newStatus,
        body.message
      ),
    }).catch(() => { }); // fire and forget
  }

  return c.json({
    message: "Order status updated successfully",
    _links: formatLinks(c, "/orders", id)
  });
});

ordersRouter.post("/:id/trackings", async (c) => {
  const id = c.req.param("id");
  const db = c.get("db");
  const body = await c.req.json();

  const [existing] = await db.select().from(schema.orders).where(eq(schema.orders.id, id));
  if (!existing) throw new Error(`Order with ID ${id} not found`);

  if (!body?.status) {
    throw new Error("VAL: Tracking status is required.");
  }

  const trackingId = crypto.randomUUID();
  await db.insert(schema.trackings).values({
    id: trackingId,
    orderId: id,
    status: body.status,
    message: body.message || null,
    location: body.location || null,
    createdAt: new Date(),
  });

  await db.update(schema.orders).set({ status: body.status }).where(eq(schema.orders.id, id));

  // ── Notification: Notify customer about tracking status change ────
  try {
    let notifyUserId = null;
    if (existing.customerEmail) {
      const [usr] = await db.select().from(schema.users).where(eq(schema.users.email, existing.customerEmail));
      if (usr) notifyUserId = usr.id;
    }
    await db.insert(schema.notifications).values({
      id: crypto.randomUUID(),
      userId: notifyUserId,
      title: `Order Tracking Updated — ${existing.invoiceId}`,
      message: `Your order ${existing.invoiceId} tracking status is now: ${body.status}. ${body.message || ''}`,
      type: "order_status",
      isRead: 0,
      createdAt: new Date().toISOString(),
    });
  } catch (err) {
    console.error("Failed to insert notification:", err);
  }

  // ── Email: Notify customer about tracking update ──
  if (existing.customerEmail && c.env.GOOGLE_SCRIPT_URL) {
    sendEmail(c.env.GOOGLE_SCRIPT_URL, c.env.EMAIL_WEBHOOK_SECRET, {
      to: existing.customerEmail,
      subject: `PlayPen House — Tracking Update for ${existing.invoiceId}`,
      text: `Hi ${existing.customerName}, your order ${existing.invoiceId} status: ${body.status}. ${body.message || ""}`,
      html: orderStatusUpdateEmailHtml(
        existing.invoiceId!,
        existing.customerName,
        body.status,
        body.message
      ),
    }).catch(() => { }); // fire and forget
  }

  return c.json({
    id: trackingId,
    message: "Tracking added successfully",
    _links: formatLinks(c, "/orders", id)
  }, 201);
});

// ── POST /orders/:id/cancel ─────────────────────────
// Customer-facing cancellation (only for Pending/Processing orders)
ordersRouter.post("/:id/cancel", async (c) => {
  const id = c.req.param("id");
  const db = c.get("db");
  const body = await c.req.json().catch(() => ({}));

  const [order] = await db.select().from(schema.orders).where(eq(schema.orders.id, id));
  if (!order) throw new Error(`Order with ID ${id} not found`);

  const status = order.status?.toLowerCase();
  if (status !== "pending" && status !== "processing") {
    return c.json({
      error: "ValidationError",
      message: `Cannot cancel an order with status "${order.status}". Only Pending or Processing orders can be cancelled.`,
    }, 422);
  }

  // Update order status
  await db.update(schema.orders)
    .set({ status: "Cancelled" })
    .where(eq(schema.orders.id, id));

  // Add tracking entry
  await db.insert(schema.trackings).values({
    id: crypto.randomUUID(),
    orderId: id,
    status: "Cancelled",
    message: body.reason
      ? `Order cancelled by customer. Reason: ${body.reason}`
      : "Order cancelled by customer.",
    createdAt: new Date(),
  });

  // Restore stock & Decrement Sold Count for cancelled items
  const orderItems = await db.select().from(schema.orderItems).where(eq(schema.orderItems.orderId, id));
  for (const item of orderItems) {
    const [product] = await db.select().from(schema.products).where(eq(schema.products.id, item.productId));
    if (product) {
      await db.update(schema.products)
        .set({
          soldCount: Math.max(0, (product.soldCount ?? 0) - item.quantity)
        })
        .where(eq(schema.products.id, item.productId));
    }
  }

  // Email customer about cancellation
  if (order.customerEmail && c.env.GOOGLE_SCRIPT_URL) {
    sendEmail(c.env.GOOGLE_SCRIPT_URL, c.env.EMAIL_WEBHOOK_SECRET, {
      to: order.customerEmail,
      subject: `PlayPen House — Order ${order.invoiceId} Cancelled`,
      text: `Hi ${order.customerName}, your order ${order.invoiceId} has been cancelled.`,
      html: orderStatusUpdateEmailHtml(
        order.invoiceId!,
        order.customerName,
        "Cancelled",
        body.reason || "Cancelled by customer"
      ),
    }).catch(() => { });
  }

  return c.json({
    message: "Order cancelled successfully.",
    _links: formatLinks(c, "/orders", id),
  });
});

// ── AUTH ───────────────────────────────────────────────────

const authRouter = new Hono<{ Bindings: Bindings; Variables: Variables }>();

// ── Rate Limit Middleware for Auth ──────────────────────
authRouter.use("*", async (c, next) => {
  const ip = c.req.header("cf-connecting-ip") || c.req.header("x-forwarded-for") || "unknown";
  const path = c.req.path;
  const key = `auth:${ip}:${path}`;

  const { limited, remaining, resetAt } = checkRateLimit(key, 10, 60_000); // 10 req/min per route

  c.header("X-RateLimit-Remaining", String(remaining));
  c.header("X-RateLimit-Reset", String(Math.ceil(resetAt / 1000)));

  if (limited) {
    return c.json({
      error: "TooManyRequests",
      message: "Too many attempts. Please wait a moment and try again.",
    }, 429);
  }

  await next();
});

// ── Helper: generate JWT ────────────────────────────────
async function generateToken(
  user: { id: string; username: string; email?: string | null; role?: string },
  secret: string
): Promise<string> {
  const payload = {
    sub: user.id,
    username: user.username,
    email: user.email || undefined,
    role: user.role || "user",
    iat: Math.floor(Date.now() / 1000),
    exp: Math.floor(Date.now() / 1000) + 7 * 24 * 60 * 60, // 7 days
  };
  return await sign(payload, secret);
}

// ── POST /auth/register ─────────────────────────────
authRouter.post("/register", async (c) => {
  const db = c.get("db");
  const body = await c.req.json().catch(() => null);

  if (!body?.username || !body?.password) {
    throw new Error("VAL: Username and password are required.");
  }

  // Check if username already exists
  const [existing] = await db
    .select()
    .from(schema.users)
    .where(eq(schema.users.username, body.username));

  if (existing) {
    throw new Error("VAL: A user with this username already exists.");
  }

  // Check if email already exists (if provided)
  if (body.email) {
    const [emailExists] = await db
      .select()
      .from(schema.users)
      .where(eq(schema.users.email, body.email));
    if (emailExists) {
      throw new Error("VAL: A user with this email already exists.");
    }
  }

  // Simple hash (for production, use bcrypt/argon2 via a worker-compatible lib)
  const encoder = new TextEncoder();
  const data = encoder.encode(body.password + "playpen-salt-2026");
  const hashBuffer = await crypto.subtle.digest("SHA-256", data);
  const hashArray = Array.from(new Uint8Array(hashBuffer));
  const passwordHash = hashArray.map(b => b.toString(16).padStart(2, "0")).join("");

  const id = crypto.randomUUID();

  await db.insert(schema.users).values({
    id,
    username: body.username,
    email: body.email || null,
    phone: body.phone || null,
    passwordHash,
    fullName: body.fullName || body.username,
    isVerified: 0,
    createdAt: new Date(),
  });

  // Generate OTP for email verification if email is provided
  if (body.email) {
    const code = String(Math.floor(100000 + Math.random() * 900000));
    const expiresAt = new Date(Date.now() + 10 * 60 * 1000); // 10 minutes

    await db.insert(schema.otpCodes).values({
      id: crypto.randomUUID(),
      userId: id,
      code,
      type: "email_verify",
      expiresAt,
      createdAt: new Date(),
    });

    // Send OTP via email
    await sendEmail(c.env.GOOGLE_SCRIPT_URL, c.env.EMAIL_WEBHOOK_SECRET, {
      to: body.email,
      subject: "PlayPen House — Verify Your Email",
      text: `Your verification code is: ${code}. It expires in 10 minutes.`,
      html: otpEmailHtml(code, body.username),
    });
  }

  return c.json({
    id,
    username: body.username,
    message: body.email
      ? "Account created! Check your email for the verification code."
      : "Account created successfully.",
    _links: formatLinks(c, "/users", id),
  }, 201);
});

// ── POST /auth/login ─────────────────────────────────
authRouter.post("/login", async (c) => {
  const db = c.get("db");
  const body = await c.req.json().catch(() => null);

  if (!body?.username || !body?.password) {
    throw new Error("VAL: Username/email and password are required.");
  }

  // Try to find by username or email
  let user;
  const [byUsername] = await db
    .select()
    .from(schema.users)
    .where(eq(schema.users.username, body.username));

  if (byUsername) {
    user = byUsername;
  } else if (body.username.includes("@")) {
    const [byEmail] = await db
      .select()
      .from(schema.users)
      .where(eq(schema.users.email, body.username));
    user = byEmail;
  }

  if (!user) {
    return c.json({ error: "Unauthorized", message: "Invalid credentials" }, 401);
  }

  // Verify password
  const encoder = new TextEncoder();
  const data = encoder.encode(body.password + "playpen-salt-2026");
  const hashBuffer = await crypto.subtle.digest("SHA-256", data);
  const hashArray = Array.from(new Uint8Array(hashBuffer));
  const passwordHash = hashArray.map(b => b.toString(16).padStart(2, "0")).join("");

  if (passwordHash !== user.passwordHash) {
    return c.json({ error: "Unauthorized", message: "Invalid credentials" }, 401);
  }

  // Generate JWT
  const token = await generateToken(
    { id: user.id, username: user.username, email: user.email },
    c.env.JWT_SECRET || "fallback-dev-secret-change-me"
  );

  return c.json({
    token,
    id: user.id,
    username: user.username,
    email: user.email,
    fullName: user.fullName,
    phone: user.phone,
    avatar: user.avatar,
    isVerified: user.isVerified,
    role: "user",
    message: "Login successful",
  });
});

// ── POST /auth/verify-otp ───────────────────────────
authRouter.post("/verify-otp", async (c) => {
  const db = c.get("db");
  const body = await c.req.json().catch(() => null);

  if (!body?.userId || !body?.code) {
    throw new Error("VAL: userId and code are required.");
  }

  // Find the most recent unused OTP for this user
  const otpRecords = await db.select().from(schema.otpCodes)
    .where(eq(schema.otpCodes.userId, body.userId));

  const validOtp = otpRecords.find(
    (otp) => otp.code === body.code && !otp.used && otp.type === "email_verify" &&
      new Date(otp.expiresAt!).getTime() > Date.now()
  );

  if (!validOtp) {
    return c.json({ error: "ValidationError", message: "Invalid or expired OTP code." }, 422);
  }

  // Mark OTP as used
  await db.update(schema.otpCodes)
    .set({ used: 1 })
    .where(eq(schema.otpCodes.id, validOtp.id));

  // Mark user as verified
  await db.update(schema.users)
    .set({ isVerified: 1 })
    .where(eq(schema.users.id, body.userId));

  return c.json({ message: "Email verified successfully." });
});

// ── POST /auth/resend-otp ───────────────────────────
authRouter.post("/resend-otp", async (c) => {
  const db = c.get("db");
  const body = await c.req.json().catch(() => null);

  if (!body?.userId) {
    throw new Error("VAL: userId is required.");
  }

  const [user] = await db.select().from(schema.users)
    .where(eq(schema.users.id, body.userId));

  if (!user) throw new Error("User not found");

  // Generate a 6-digit OTP
  const code = String(Math.floor(100000 + Math.random() * 900000));
  const expiresAt = new Date(Date.now() + 10 * 60 * 1000); // 10 minutes

  await db.insert(schema.otpCodes).values({
    id: crypto.randomUUID(),
    userId: body.userId,
    code,
    type: "email_verify",
    expiresAt,
    createdAt: new Date(),
  });

  // Send OTP via email
  if (user.email) {
    await sendEmail(c.env.GOOGLE_SCRIPT_URL, c.env.EMAIL_WEBHOOK_SECRET, {
      to: user.email,
      subject: "PlayPen House — Your Verification Code",
      text: `Your verification code is: ${code}. It expires in 10 minutes.`,
      html: otpEmailHtml(code, user.username),
    });
  }

  return c.json({ message: "OTP sent successfully." });
});

// ── POST /auth/forgot-password ──────────────────────
authRouter.post("/forgot-password", async (c) => {
  const db = c.get("db");
  const body = await c.req.json().catch(() => null);

  if (!body?.email) {
    throw new Error("VAL: Email is required.");
  }

  const [user] = await db.select().from(schema.users)
    .where(eq(schema.users.email, body.email));

  // Don't reveal if user exists
  if (!user) {
    return c.json({ message: "If an account with that email exists, a reset code has been sent." });
  }

  const code = String(Math.floor(100000 + Math.random() * 900000));
  const expiresAt = new Date(Date.now() + 10 * 60 * 1000);

  await db.insert(schema.otpCodes).values({
    id: crypto.randomUUID(),
    userId: user.id,
    code,
    type: "password_reset",
    expiresAt,
    createdAt: new Date(),
  });

  // Send reset email
  await sendEmail(c.env.GOOGLE_SCRIPT_URL, c.env.EMAIL_WEBHOOK_SECRET, {
    to: user.email!,
    subject: "PlayPen House — Password Reset Code",
    text: `Your password reset code is: ${code}. It expires in 10 minutes.`,
    html: passwordResetEmailHtml(code, user.email!),
  });

  return c.json({ message: "If an account with that email exists, a reset code has been sent." });
});

// ── POST /auth/reset-password ───────────────────────
authRouter.post("/reset-password", async (c) => {
  const db = c.get("db");
  const body = await c.req.json().catch(() => null);

  if (!body?.email || !body?.code || !body?.newPassword) {
    throw new Error("VAL: Email, code, and new password are required.");
  }

  const [user] = await db.select().from(schema.users)
    .where(eq(schema.users.email, body.email));

  if (!user) {
    return c.json({ error: "ValidationError", message: "Invalid reset request." }, 422);
  }

  const otpRecords = await db.select().from(schema.otpCodes)
    .where(eq(schema.otpCodes.userId, user.id));

  const validOtp = otpRecords.find(
    (otp) => otp.code === body.code && !otp.used && otp.type === "password_reset" &&
      new Date(otp.expiresAt!).getTime() > Date.now()
  );

  if (!validOtp) {
    return c.json({ error: "ValidationError", message: "Invalid or expired reset code." }, 422);
  }

  // Mark OTP as used
  await db.update(schema.otpCodes)
    .set({ used: 1 })
    .where(eq(schema.otpCodes.id, validOtp.id));

  // Hash new password
  const encoder = new TextEncoder();
  const data = encoder.encode(body.newPassword + "playpen-salt-2026");
  const hashBuffer = await crypto.subtle.digest("SHA-256", data);
  const hashArray = Array.from(new Uint8Array(hashBuffer));
  const passwordHash = hashArray.map(b => b.toString(16).padStart(2, "0")).join("");

  await db.update(schema.users)
    .set({ passwordHash })
    .where(eq(schema.users.id, user.id));

  return c.json({ message: "Password reset successfully. You can now log in." });
});

// ── USERS ──────────────────────────────────────────────────

const usersRouter = new Hono<{ Bindings: Bindings; Variables: Variables }>();

// ── GET /users ──────────────────────────────────────
// Admin: list all users with search and pagination
usersRouter.get("/", async (c) => {
  const db = c.get("db");
  const search = c.req.query("search");
  const page = parseInt(c.req.query("page") || "1");
  const limit = parseInt(c.req.query("limit") || "20");
  const offset = (page - 1) * limit;

  // Count total
  let countResult;
  if (search) {
    countResult = await db.select({ count: sql<number>`count(*)` }).from(schema.users)
      .where(like(schema.users.username, `%${search}%`));
  } else {
    countResult = await db.select({ count: sql<number>`count(*)` }).from(schema.users);
  }
  const total = countResult[0]?.count || 0;

  // Fetch page
  let query = db.select({
    id: schema.users.id,
    username: schema.users.username,
    email: schema.users.email,
    phone: schema.users.phone,
    fullName: schema.users.fullName,
    avatar: schema.users.avatar,
    role: schema.users.role,
    isVerified: schema.users.isVerified,
    isBlocked: schema.users.isBlocked,
    createdAt: schema.users.createdAt,
  }).from(schema.users);

  if (search) {
    query = query.where(like(schema.users.username, `%${search}%`)) as any;
  }

  const rows = await (query as any).orderBy(desc(schema.users.createdAt)).limit(limit).offset(offset);

  return c.json(createPaginatedResponse(
    rows.map((r: any) => ({ ...r, _links: formatLinks(c, "/users", r.id) })),
    total,
    page,
    limit,
    formatLinks(c, "/users")
  ));
});

// ── GET /users/:id ──────────────────────────────────
usersRouter.get("/:id", async (c) => {
  const id = c.req.param("id");
  const db = c.get("db");

  const [user] = await db.select({
    id: schema.users.id,
    username: schema.users.username,
    email: schema.users.email,
    phone: schema.users.phone,
    fullName: schema.users.fullName,
    avatar: schema.users.avatar,
    role: schema.users.role,
    isVerified: schema.users.isVerified,
    isBlocked: schema.users.isBlocked,
    createdAt: schema.users.createdAt,
  }).from(schema.users).where(eq(schema.users.id, id));

  if (!user) throw new Error(`User with ID ${id} not found`);

  return c.json({ ...user, _links: formatLinks(c, "/users", id) });
});

// ── PATCH /users/:id ────────────────────────────────
usersRouter.patch("/:id", async (c) => {
  const id = c.req.param("id");
  const db = c.get("db");
  const body = await c.req.json();

  const [existing] = await db.select().from(schema.users).where(eq(schema.users.id, id));
  if (!existing) throw new Error(`User with ID ${id} not found`);

  const updates: Record<string, any> = {};
  if (body.fullName !== undefined) updates.fullName = body.fullName;
  if (body.phone !== undefined) updates.phone = body.phone;
  if (body.avatar !== undefined) updates.avatar = body.avatar;
  if (body.isVerified !== undefined) updates.isVerified = body.isVerified;
  if (body.isBlocked !== undefined) updates.isBlocked = body.isBlocked;
  if (body.role !== undefined) updates.role = body.role;

  if (Object.keys(updates).length > 0) {
    await db.update(schema.users).set(updates).where(eq(schema.users.id, id));
  }

  return c.json({
    message: "User updated successfully",
    _links: formatLinks(c, "/users", id),
  });
});

// ── PATCH /users/:id/password ───────────────────────
usersRouter.patch("/:id/password", async (c) => {
  const id = c.req.param("id");
  const db = c.get("db");
  const body = await c.req.json();

  if (!body?.currentPassword || !body?.newPassword) {
    throw new Error("VAL: Current password and new password are required.");
  }

  const [user] = await db.select().from(schema.users).where(eq(schema.users.id, id));
  if (!user) throw new Error(`User with ID ${id} not found`);

  // Verify current password
  const encoder = new TextEncoder();
  const currentData = encoder.encode(body.currentPassword + "playpen-salt-2026");
  const currentHash = Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256", currentData)))
    .map(b => b.toString(16).padStart(2, "0")).join("");

  if (currentHash !== user.passwordHash) {
    return c.json({ error: "Unauthorized", message: "Current password is incorrect" }, 401);
  }

  // Hash new password
  const newData = encoder.encode(body.newPassword + "playpen-salt-2026");
  const newHash = Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256", newData)))
    .map(b => b.toString(16).padStart(2, "0")).join("");

  await db.update(schema.users).set({ passwordHash: newHash }).where(eq(schema.users.id, id));

  return c.json({ message: "Password updated successfully" });
});

// ── PATCH /users/:id/block ──────────────────────────
usersRouter.patch("/:id/block", async (c) => {
  const id = c.req.param("id");
  const db = c.get("db");

  const [user] = await db.select().from(schema.users).where(eq(schema.users.id, id));
  if (!user) throw new Error(`User with ID ${id} not found`);

  const newStatus = user.isBlocked ? 0 : 1;
  await db.update(schema.users).set({ isBlocked: newStatus }).where(eq(schema.users.id, id));

  return c.json({
    message: newStatus ? "User blocked successfully" : "User unblocked successfully",
    isBlocked: newStatus,
  });
});

// ── PATCH /users/:id/verify ─────────────────────────
usersRouter.patch("/:id/verify", async (c) => {
  const id = c.req.param("id");
  const db = c.get("db");

  const [user] = await db.select().from(schema.users).where(eq(schema.users.id, id));
  if (!user) throw new Error(`User with ID ${id} not found`);

  const newStatus = user.isVerified ? 0 : 1;
  await db.update(schema.users).set({ isVerified: newStatus }).where(eq(schema.users.id, id));

  return c.json({
    message: newStatus ? "User verified successfully" : "User unverified",
    isVerified: newStatus,
  });
});

// ── ADDRESSES ──────────────────────────────────────────────

const addressesRouter = new Hono<{ Bindings: Bindings; Variables: Variables }>();

// ── GET /addresses?userId=xxx ───────────────────────
addressesRouter.get("/", async (c) => {
  const db = c.get("db");
  const userId = c.req.query("userId");

  if (!userId) {
    throw new Error("VAL: userId query parameter is required.");
  }

  const rows = await db.query.addresses.findMany({
    where: (a: any, { eq }: any) => eq(a.userId, userId),
    orderBy: (a: any, { desc }: any) => [desc(a.isDefault), desc(a.createdAt)],
  });

  return c.json({
    items: rows.map((r: any) => ({ ...r, _links: formatLinks(c, "/addresses", r.id) })),
    _links: formatLinks(c, "/addresses"),
  });
});

// ── POST /addresses ─────────────────────────────────
addressesRouter.post("/", async (c) => {
  const db = c.get("db");
  const body = await c.req.json().catch(() => null);

  if (!body?.userId || !body?.fullName || !body?.phone || !body?.address) {
    throw new Error("VAL: userId, fullName, phone, and address are required.");
  }

  const id = crypto.randomUUID();

  // If this is set as default, unset all others
  if (body.isDefault) {
    await db.update(schema.addresses)
      .set({ isDefault: 0 })
      .where(eq(schema.addresses.userId, body.userId));
  }

  await db.insert(schema.addresses).values({
    id,
    userId: body.userId,
    label: body.label || "Home",
    fullName: body.fullName,
    phone: body.phone,
    address: body.address,
    city: body.city || null,
    postalCode: body.postalCode || null,
    isDefault: body.isDefault ? 1 : 0,
    createdAt: new Date(),
  });

  return c.json({
    id,
    message: "Address added successfully",
    _links: formatLinks(c, "/addresses", id),
  }, 201);
});

// ── PATCH /addresses/:id ────────────────────────────
addressesRouter.patch("/:id", async (c) => {
  const id = c.req.param("id");
  const db = c.get("db");
  const body = await c.req.json();

  const [existing] = await db.select().from(schema.addresses).where(eq(schema.addresses.id, id));
  if (!existing) throw new Error(`Address with ID ${id} not found`);

  const updates: Record<string, any> = {};
  if (body.label !== undefined) updates.label = body.label;
  if (body.fullName !== undefined) updates.fullName = body.fullName;
  if (body.phone !== undefined) updates.phone = body.phone;
  if (body.address !== undefined) updates.address = body.address;
  if (body.city !== undefined) updates.city = body.city;
  if (body.postalCode !== undefined) updates.postalCode = body.postalCode;

  if (body.isDefault) {
    await db.update(schema.addresses)
      .set({ isDefault: 0 })
      .where(eq(schema.addresses.userId, existing.userId));
    updates.isDefault = 1;
  }

  if (Object.keys(updates).length > 0) {
    await db.update(schema.addresses).set(updates).where(eq(schema.addresses.id, id));
  }

  return c.json({
    message: "Address updated successfully",
    _links: formatLinks(c, "/addresses", id),
  });
});

// ── DELETE /addresses/:id ───────────────────────────
addressesRouter.delete("/:id", async (c) => {
  const id = c.req.param("id");
  const db = c.get("db");

  const [existing] = await db.select().from(schema.addresses).where(eq(schema.addresses.id, id));
  if (!existing) throw new Error(`Address with ID ${id} not found`);

  await db.delete(schema.addresses).where(eq(schema.addresses.id, id));

  return c.json({ message: "Address deleted successfully" });
});

// ── REVIEWS ────────────────────────────────────────────────

const reviewsRouter = new Hono<{ Bindings: Bindings; Variables: Variables }>();

// ── GET /reviews?productId=xxx ──────────────────────
// Also supports ?userId=xxx for "My Reviews" page
reviewsRouter.get("/", async (c) => {
  const db = c.get("db");
  const productId = c.req.query("productId");
  const userId = c.req.query("userId");

  let whereClause;
  if (productId) {
    whereClause = (r: any, { eq }: any) => eq(r.productId, productId);
  } else if (userId) {
    whereClause = (r: any, { eq }: any) => eq(r.userId, userId);
  }

  const rows = await db.query.reviews.findMany({
    where: whereClause,
    orderBy: (r: any, { desc }: any) => [desc(r.createdAt)],
  });

  // Calculate aggregate stats if filtering by product
  let stats = null;
  if (productId && rows.length > 0) {
    const total = rows.length;
    const avgRating = rows.reduce((sum: number, r: any) => sum + r.rating, 0) / total;
    const distribution = [1, 2, 3, 4, 5].map(star => ({
      stars: star,
      count: rows.filter(r => r.rating === star).length,
      percentage: Math.round((rows.filter(r => r.rating === star).length / total) * 100),
    }));
    stats = { averageRating: Math.round(avgRating * 10) / 10, totalReviews: total, distribution };
  }

  return c.json({
    items: rows.map((r: any) => ({ ...r, _links: formatLinks(c, "/reviews", r.id) })),
    stats,
    _links: formatLinks(c, "/reviews"),
  });
});

// ── POST /reviews ───────────────────────────────────
reviewsRouter.post("/", async (c) => {
  const db = c.get("db");
  const body = await c.req.json().catch(() => null);

  if (!body?.productId || !body?.userId || !body?.rating) {
    throw new Error("VAL: productId, userId, and rating are required.");
  }

  if (body.rating < 1 || body.rating > 5) {
    throw new Error("VAL: Rating must be between 1 and 5.");
  }

  // Check for duplicate review
  const existingReviews = await db.select().from(schema.reviews)
    .where(and(
      eq(schema.reviews.productId, body.productId),
      eq(schema.reviews.userId, body.userId)
    ));

  if (existingReviews.length > 0) {
    throw new Error("VAL: You have already reviewed this product.");
  }

  // Check if this is a verified purchase
  let isVerified = 0;
  try {
    const userOrders = await db.select().from(schema.orders)
      .where(eq(schema.orders.userId, body.userId));
    for (const order of userOrders) {
      if (order.status?.toLowerCase() === "delivered") {
        const items = await db.select().from(schema.orderItems)
          .where(and(
            eq(schema.orderItems.orderId, order.id),
            eq(schema.orderItems.productId, body.productId)
          ));
        if (items.length > 0) { isVerified = 1; break; }
      }
    }
  } catch { /* non-critical */ }

  const id = crypto.randomUUID();

  await db.insert(schema.reviews).values({
    id,
    productId: body.productId,
    userId: body.userId,
    username: body.username || "Anonymous",
    rating: body.rating,
    title: body.title || null,
    content: body.content || null,
    images: body.images ? JSON.stringify(body.images) : null,
    isVerified,
    createdAt: new Date(),
  });

  // Update product aggregate rating
  const allReviews = await db.select().from(schema.reviews)
    .where(eq(schema.reviews.productId, body.productId));
  const avgRating = allReviews.reduce((sum: number, r: any) => sum + r.rating, 0) / allReviews.length;

  await db.update(schema.products).set({
    rating: Math.round(avgRating * 10) / 10,
    reviewCount: allReviews.length,
  }).where(eq(schema.products.id, body.productId));

  return c.json({
    id,
    isVerified,
    message: "Review submitted successfully",
    _links: formatLinks(c, "/reviews", id),
  }, 201);
});

// ── PATCH /reviews/:id ──────────────────────────────
reviewsRouter.patch("/:id", async (c) => {
  const id = c.req.param("id");
  const db = c.get("db");
  const body = await c.req.json();

  const [existing] = await db.select().from(schema.reviews).where(eq(schema.reviews.id, id));
  if (!existing) throw new Error(`Review with ID ${id} not found`);

  const updates: Record<string, any> = {};
  if (body.rating !== undefined) updates.rating = body.rating;
  if (body.title !== undefined) updates.title = body.title;
  if (body.content !== undefined) updates.content = body.content;
  if (body.images !== undefined) updates.images = JSON.stringify(body.images);
  if (body.status !== undefined) updates.status = body.status;

  if (Object.keys(updates).length > 0) {
    await db.update(schema.reviews).set(updates).where(eq(schema.reviews.id, id));
  }

  // Re-calculate product aggregate if rating changed
  if (body.rating !== undefined) {
    const allReviews = await db.select().from(schema.reviews)
      .where(eq(schema.reviews.productId, existing.productId));
    const avgRating = allReviews.reduce((sum: number, r: any) => sum + r.rating, 0) / allReviews.length;
    await db.update(schema.products).set({
      rating: Math.round(avgRating * 10) / 10,
    }).where(eq(schema.products.id, existing.productId));
  }

  return c.json({ message: "Review updated successfully", _links: formatLinks(c, "/reviews", id) });
});

// ── DELETE /reviews/:id ─────────────────────────────
reviewsRouter.delete("/:id", async (c) => {
  const id = c.req.param("id");
  const db = c.get("db");

  const [existing] = await db.select().from(schema.reviews).where(eq(schema.reviews.id, id));
  if (!existing) throw new Error(`Review with ID ${id} not found`);

  await db.delete(schema.reviews).where(eq(schema.reviews.id, id));

  // Re-calculate product aggregate
  const remaining = await db.select().from(schema.reviews)
    .where(eq(schema.reviews.productId, existing.productId));
  const avgRating = remaining.length > 0
    ? remaining.reduce((sum: number, r: any) => sum + r.rating, 0) / remaining.length
    : 0;

  await db.update(schema.products).set({
    rating: Math.round(avgRating * 10) / 10,
    reviewCount: remaining.length,
  }).where(eq(schema.products.id, existing.productId));

  return c.json({ message: "Review deleted successfully" });
});

// ── RETURNS ────────────────────────────────────────────────

const returnsRouter = new Hono<{ Bindings: Bindings; Variables: Variables }>();

// ── GET /returns?userId=xxx ─────────────────────────
// Also supports ?type=return or ?type=cancellation
returnsRouter.get("/", async (c) => {
  const db = c.get("db");
  const userId = c.req.query("userId");
  const type = c.req.query("type"); // "return" | "cancellation"

  const rows = await db.query.returns.findMany({
    where: (r: any, { eq, and }: any) => {
      const conditions = [];
      if (userId) conditions.push(eq(r.userId, userId));
      if (type) conditions.push(eq(r.type, type));
      return conditions.length > 1 ? and(...conditions) : conditions[0];
    },
    orderBy: (r: any, { desc }: any) => [desc(r.createdAt)],
  });

  return c.json({
    items: rows.map((r: any) => ({ ...r, _links: formatLinks(c, "/returns", r.id) })),
    _links: formatLinks(c, "/returns"),
  });
});

// ── POST /returns ───────────────────────────────────
// Used for both returns and cancellations
returnsRouter.post("/", async (c) => {
  const db = c.get("db");
  const body = await c.req.json().catch(() => null);

  if (!body?.orderId || !body?.userId || !body?.reason || !body?.type) {
    throw new Error("VAL: orderId, userId, reason, and type are required.");
  }

  if (!["return", "cancellation"].includes(body.type)) {
    throw new Error("VAL: type must be 'return' or 'cancellation'.");
  }

  // Validate order exists and belongs to user
  const [order] = await db.select().from(schema.orders)
    .where(eq(schema.orders.id, body.orderId));

  if (!order) throw new Error(`Order with ID ${body.orderId} not found`);

  // Business rules
  const status = order.status?.toLowerCase();
  if (body.type === "cancellation") {
    if (status !== "pending" && status !== "processing") {
      throw new Error("VAL: Orders can only be cancelled when in Pending or Processing status.");
    }
  } else if (body.type === "return") {
    if (status !== "delivered") {
      throw new Error("VAL: Returns can only be requested for Delivered orders.");
    }
    // Check 7-day window
    if (order.createdAt) {
      const deliveredDate = new Date(order.createdAt);
      const daysSince = (Date.now() - deliveredDate.getTime()) / (1000 * 60 * 60 * 24);
      if (daysSince > 7) {
        throw new Error("VAL: Return window has expired (7 days from delivery).");
      }
    }
  }

  // Check for duplicate request
  const existingReturns = await db.select().from(schema.returns)
    .where(and(
      eq(schema.returns.orderId, body.orderId),
      eq(schema.returns.type, body.type)
    ));
  if (existingReturns.length > 0) {
    throw new Error(`VAL: A ${body.type} request already exists for this order.`);
  }

  const id = crypto.randomUUID();

  await db.insert(schema.returns).values({
    id,
    orderId: body.orderId,
    userId: body.userId,
    reason: body.reason,
    details: body.details || null,
    images: body.images ? JSON.stringify(body.images) : null,
    status: "Requested",
    type: body.type,
    createdAt: new Date(),
  });

  // If cancellation, update order status immediately
  if (body.type === "cancellation") {
    await db.update(schema.orders)
      .set({ status: "Cancelled" })
      .where(eq(schema.orders.id, body.orderId));

    // Add tracking entry
    await db.insert(schema.trackings).values({
      id: crypto.randomUUID(),
      orderId: body.orderId,
      status: "Cancelled",
      message: `Order cancelled by customer. Reason: ${body.reason}`,
      createdAt: new Date(),
    });
  }

  return c.json({
    id,
    message: `${body.type === "cancellation" ? "Cancellation" : "Return"} request submitted successfully`,
    _links: formatLinks(c, "/returns", id),
  }, 201);
});

// ── PATCH /returns/:id ─────────────────────────────
// Admin: update status + notes
returnsRouter.patch("/:id", async (c) => {
  const id = c.req.param("id");
  const db = c.get("db");
  const body = await c.req.json();

  const [existing] = await db.select().from(schema.returns).where(eq(schema.returns.id, id));
  if (!existing) throw new Error(`Return request with ID ${id} not found`);

  const updates: Record<string, any> = {};
  if (body.status) updates.status = body.status;
  if (body.adminNotes !== undefined) updates.adminNotes = body.adminNotes;

  if (Object.keys(updates).length > 0) {
    await db.update(schema.returns).set(updates).where(eq(schema.returns.id, id));
  }

  return c.json({
    message: "Return request updated successfully",
    _links: formatLinks(c, "/returns", id),
  });
});

// ── PATCH /returns/:id/status ───────────────────────
// Admin-only: approve/reject returns (legacy — kept for compatibility)
returnsRouter.patch("/:id/status", async (c) => {
  const id = c.req.param("id");
  const db = c.get("db");
  const body = await c.req.json();

  const [existing] = await db.select().from(schema.returns).where(eq(schema.returns.id, id));
  if (!existing) throw new Error(`Return request with ID ${id} not found`);

  const updates: Record<string, any> = {};
  if (body.status) updates.status = body.status;
  if (body.adminNotes) updates.adminNotes = body.adminNotes;

  if (Object.keys(updates).length > 0) {
    await db.update(schema.returns).set(updates).where(eq(schema.returns.id, id));
  }

  return c.json({
    message: "Return request updated successfully",
    _links: formatLinks(c, "/returns", id),
  });
});

// ── SETTINGS ───────────────────────────────────────────────

const settingsRouter = new Hono<{ Bindings: Bindings; Variables: Variables }>();

// ── POST /settings/test-email ───────────────────────
// Sends a test email to verify Gmail integration is working.
settingsRouter.post("/test-email", async (c) => {
  const body = await c.req.json().catch(() => null);

  if (!body?.email) {
    throw new Error("VAL: Email address is required.");
  }

  if (!c.env.GOOGLE_SCRIPT_URL) {
    return c.json({
      error: "ConfigError",
      message: "GOOGLE_SCRIPT_URL is not configured. Please set it in your environment variables.",
    }, 503);
  }

  const success = await sendEmail(c.env.GOOGLE_SCRIPT_URL, c.env.EMAIL_WEBHOOK_SECRET, {
    to: body.email,
    subject: "PlayPen House — Test Email ✅",
    text: "If you received this, your email notifications are working correctly!",
    html: `
      <div style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 480px; margin: 0 auto; padding: 32px; background: #fff; border-radius: 16px; border: 2px solid #22c55e;">
        <div style="text-align: center;">
          <h1 style="color: #1a1a2e; font-size: 24px; margin: 0;">🏠 PlayPen House</h1>
          <p style="color: #22c55e; font-size: 20px; font-weight: 700; margin: 16px 0;">✅ Email Integration Working!</p>
          <p style="color: #666; font-size: 14px;">This is a test email from your admin panel. Your notification system is configured correctly.</p>
          <hr style="border: none; border-top: 1px solid #eee; margin: 24px 0;" />
          <p style="color: #aaa; font-size: 11px;">Sent at: ${new Date().toISOString()}</p>
        </div>
      </div>
    `,
  });

  if (success) {
    return c.json({ message: "Test email sent successfully!" });
  } else {
    return c.json({ error: "EmailError", message: "Failed to send test email. Check your GOOGLE_SCRIPT_URL configuration." }, 500);
  }
});

// ── COUPONS ────────────────────────────────────────────────

const couponsRouter = new Hono<{ Bindings: Bindings; Variables: Variables }>();

// ── GET /coupons ────────────────────────────────────
couponsRouter.get("/", async (c) => {
  const db = c.get("db");
  const rows = await db.query.coupons.findMany({
    orderBy: (cp: any, { desc }: any) => [desc(cp.createdAt)],
  });
  return c.json({
    items: rows.map((r) => ({ ...r, _links: formatLinks(c, "/coupons", r.id) })),
    _links: formatLinks(c, "/coupons"),
  });
});

// ── GET /coupons/validate?code=XXX&total=100 ────────
// Customer-facing: check if a coupon is valid
couponsRouter.get("/validate", async (c) => {
  const db = c.get("db");
  const code = c.req.query("code")?.toUpperCase();
  const orderTotal = parseFloat(c.req.query("total") || "0");

  if (!code) throw new Error("VAL: Coupon code is required.");

  const [coupon] = await db.select().from(schema.coupons).where(eq(schema.coupons.code, code));

  if (!coupon || !coupon.isActive) {
    return c.json({ valid: false, message: "Invalid or expired coupon code." }, 404);
  }

  // Check expiration
  if (coupon.expiresAt && new Date(coupon.expiresAt).getTime() < Date.now()) {
    return c.json({ valid: false, message: "This coupon has expired." });
  }

  // Check start date
  if (coupon.startsAt && new Date(coupon.startsAt).getTime() > Date.now()) {
    return c.json({ valid: false, message: "This coupon is not yet active." });
  }

  // Check usage limit
  if (coupon.usageLimit && (coupon.usedCount ?? 0) >= coupon.usageLimit) {
    return c.json({ valid: false, message: "This coupon has reached its usage limit." });
  }

  // Check minimum order
  if (coupon.minOrderAmount && orderTotal < coupon.minOrderAmount) {
    return c.json({
      valid: false,
      message: `Minimum order amount of ৳${coupon.minOrderAmount.toLocaleString()} required.`,
    });
  }

  // Calculate discount
  let discount = 0;
  if (coupon.type === "percentage") {
    discount = (orderTotal * coupon.value) / 100;
    if (coupon.maxDiscount && discount > coupon.maxDiscount) {
      discount = coupon.maxDiscount;
    }
  } else {
    discount = coupon.value;
  }
  discount = Math.min(discount, orderTotal); // Can't exceed order total

  return c.json({
    valid: true,
    coupon: {
      code: coupon.code,
      description: coupon.description,
      type: coupon.type,
      value: coupon.value,
    },
    discount: Math.round(discount * 100) / 100,
    message: `Coupon applied! You save ৳${discount.toLocaleString()}.`,
  });
});

// ── POST /coupons ───────────────────────────────────
couponsRouter.post("/", async (c) => {
  const db = c.get("db");
  const body = await c.req.json().catch(() => null);

  if (!body?.code || !body?.type || body?.value === undefined) {
    throw new Error("VAL: Code, type, and value are required.");
  }

  const id = crypto.randomUUID();
  await db.insert(schema.coupons).values({
    id,
    code: body.code.toUpperCase(),
    description: body.description || null,
    type: body.type,
    value: body.value,
    minOrderAmount: body.minOrderAmount || 0,
    maxDiscount: body.maxDiscount || null,
    usageLimit: body.usageLimit || null,
    isActive: body.isActive ?? 1,
    startsAt: body.startsAt ? new Date(body.startsAt) : null,
    expiresAt: body.expiresAt ? new Date(body.expiresAt) : null,
    createdAt: new Date(),
  });

  return c.json({ id, message: "Coupon created successfully", _links: formatLinks(c, "/coupons", id) }, 201);
});

// ── PATCH /coupons/:id ──────────────────────────────
couponsRouter.patch("/:id", async (c) => {
  const id = c.req.param("id");
  const db = c.get("db");
  const body = await c.req.json();

  const [existing] = await db.select().from(schema.coupons).where(eq(schema.coupons.id, id));
  if (!existing) throw new Error(`Coupon with ID ${id} not found`);

  const updates: Record<string, any> = {};
  if (body.code !== undefined) updates.code = body.code.toUpperCase();
  if (body.description !== undefined) updates.description = body.description;
  if (body.type !== undefined) updates.type = body.type;
  if (body.value !== undefined) updates.value = body.value;
  if (body.minOrderAmount !== undefined) updates.minOrderAmount = body.minOrderAmount;
  if (body.maxDiscount !== undefined) updates.maxDiscount = body.maxDiscount;
  if (body.usageLimit !== undefined) updates.usageLimit = body.usageLimit;
  if (body.isActive !== undefined) updates.isActive = body.isActive;
  if (body.startsAt !== undefined) updates.startsAt = body.startsAt ? new Date(body.startsAt) : null;
  if (body.expiresAt !== undefined) updates.expiresAt = body.expiresAt ? new Date(body.expiresAt) : null;

  if (Object.keys(updates).length > 0) {
    await db.update(schema.coupons).set(updates).where(eq(schema.coupons.id, id));
  }

  return c.json({ message: "Coupon updated successfully", _links: formatLinks(c, "/coupons", id) });
});

// ── DELETE /coupons/:id ─────────────────────────────
couponsRouter.delete("/:id", async (c) => {
  const id = c.req.param("id");
  const db = c.get("db");

  await db.delete(schema.coupons).where(eq(schema.coupons.id, id));
  return c.json({ message: "Coupon deleted successfully" });
});

// ── DASHBOARD ──────────────────────────────────────────────

const dashboardRouter = new Hono<{ Bindings: Bindings; Variables: Variables }>();

// ── GET /dashboard/stats ────────────────────────────
// Returns real aggregated stats for the admin dashboard
dashboardRouter.get("/stats", async (c) => {
  const db = c.get("db");

  // Counts
  const [prodCount] = await db.select({ count: sql<number>`count(*)` }).from(schema.products);
  const [catCount] = await db.select({ count: sql<number>`count(*)` }).from(schema.categories);
  const [userCount] = await db.select({ count: sql<number>`count(*)` }).from(schema.users);
  const [orderCount] = await db.select({ count: sql<number>`count(*)` }).from(schema.orders);
  const [reviewCount] = await db.select({ count: sql<number>`count(*)` }).from(schema.reviews);

  // Revenue
  const [revenueResult] = await db.select({
    total: sql<number>`COALESCE(SUM(total_amount), 0)`,
  }).from(schema.orders)
    .where(sql`lower(status) != 'cancelled'`);

  // Orders by status
  const statusRows = await db.select({
    status: schema.orders.status,
    count: sql<number>`count(*)`,
  }).from(schema.orders).groupBy(schema.orders.status);

  const ordersByStatus: Record<string, number> = {};
  statusRows.forEach((r) => { ordersByStatus[r.status || 'Unknown'] = r.count; });

  // Recent orders (last 5)
  const recentOrders = await db.select({
    id: schema.orders.id,
    invoiceId: schema.orders.invoiceId,
    customerName: schema.orders.customerName,
    status: schema.orders.status,
    totalAmount: schema.orders.totalAmount,
    createdAt: schema.orders.createdAt,
  }).from(schema.orders).orderBy(desc(schema.orders.createdAt)).limit(5);

  // Low stock products (stock < threshold or stock < 5)
  const lowStockProducts = await db.select({
    id: schema.products.id,
    title: schema.products.title,
    stock: schema.products.stock,
    lowStockThreshold: schema.products.lowStockThreshold,
  }).from(schema.products)
    .where(sql`stock < COALESCE(low_stock_threshold, 5) AND is_active = 1`)
    .limit(10);

  // Monthly revenue (last 6 months)
  const monthlyRevenue = await db.select({
    month: sql<string>`strftime('%Y-%m', datetime(created_at, 'unixepoch'))`,
    total: sql<number>`COALESCE(SUM(total_amount), 0)`,
    count: sql<number>`count(*)`,
  }).from(schema.orders)
    .where(sql`lower(status) != 'cancelled'`)
    .groupBy(sql`strftime('%Y-%m', datetime(created_at, 'unixepoch'))`)
    .orderBy(sql`strftime('%Y-%m', datetime(created_at, 'unixepoch')) DESC`)
    .limit(6);

  return c.json({
    counts: {
      products: prodCount.count,
      categories: catCount.count,
      users: userCount.count,
      orders: orderCount.count,
      reviews: reviewCount.count,
    },
    revenue: revenueResult.total,
    ordersByStatus,
    recentOrders,
    lowStockProducts,
    monthlyRevenue: monthlyRevenue.reverse(),
  });
});

// ── WALLET ─────────────────────────────────────────────────

const walletRouter = new Hono<{ Bindings: Bindings; Variables: Variables }>();

// ── GET /wallet?userId=xxx ───────────────────────
walletRouter.get("/", async (c) => {
  const db = c.get("db");
  const userId = c.req.query("userId");

  if (!userId) {
    throw new Error("VAL: userId query parameter is required.");
  }

  const rows = await db.query.walletTransactions.findMany({
    where: (t: any, { eq }: any) => eq(t.userId, userId),
    orderBy: (t: any, { desc }: any) => [desc(t.createdAt)],
  });

  // Calculate current balance (latest balanceAfter)
  const balance = rows.length > 0 ? (rows[0].balanceAfter ?? 0) : 0;

  return c.json({
    balance,
    items: rows.map((r: any) => ({ ...r, _links: formatLinks(c, "/wallet", r.id) })),
    _links: formatLinks(c, "/wallet"),
  });
});

// ── POST /wallet/topup ───────────────────────────
walletRouter.post("/topup", async (c) => {
  const db = c.get("db");
  const body = await c.req.json().catch(() => null);

  if (!body?.userId || !body?.amount || body.amount <= 0) {
    throw new Error("VAL: userId and a positive amount are required.");
  }

  const id = crypto.randomUUID();
  const userId = body.userId;
  const amount = Number(body.amount);

  // Get current balance
  const rows = await db.query.walletTransactions.findMany({
    where: (t: any, { eq }: any) => eq(t.userId, userId),
    orderBy: (t: any, { desc }: any) => [desc(t.createdAt)],
    limit: 1,
  });

  const currentBalance = rows.length > 0 ? (rows[0].balanceAfter ?? 0) : 0;
  const newBalance = currentBalance + amount;

  await db.insert(schema.walletTransactions).values({
    id,
    userId,
    amount,
    type: "credit",
    reference: body.reference || "Top-up",
    balanceAfter: newBalance,
    createdAt: new Date(),
  });

  return c.json({
    id,
    balanceAfter: newBalance,
    message: "Wallet topped up successfully",
    _links: formatLinks(c, "/wallet", id),
  }, 201);
});

// ── POST /wallet/charge ──────────────────────────
walletRouter.post("/charge", async (c) => {
  const db = c.get("db");
  const body = await c.req.json().catch(() => null);

  if (!body?.userId || !body?.amount || body.amount <= 0) {
    throw new Error("VAL: userId and a positive amount are required.");
  }

  const id = crypto.randomUUID();
  const userId = body.userId;
  const amount = Number(body.amount);

  // Get current balance
  const rows = await db.query.walletTransactions.findMany({
    where: (t: any, { eq }: any) => eq(t.userId, userId),
    orderBy: (t: any, { desc }: any) => [desc(t.createdAt)],
    limit: 1,
  });

  const currentBalance = rows.length > 0 ? (rows[0].balanceAfter ?? 0) : 0;

  if (currentBalance < amount) {
    throw new Error("VAL: Insufficient wallet balance.");
  }

  const newBalance = currentBalance - amount;

  await db.insert(schema.walletTransactions).values({
    id,
    userId,
    amount,
    type: "debit",
    reference: body.reference || "Payment",
    balanceAfter: newBalance,
    createdAt: new Date(),
  });

  return c.json({
    id,
    balanceAfter: newBalance,
    message: "Wallet charged successfully",
    _links: formatLinks(c, "/wallet", id),
  }, 201);
});

// ── NOTIFICATIONS ──────────────────────────────────────────

const notificationsRouter = new Hono<{ Bindings: Bindings; Variables: Variables }>();

// GET /api/v1/notifications
// Retrieves notifications for the user + all broadcasts
notificationsRouter.get("/", async (c) => {
  try {
    const db = c.get("db");
    const userId = c.req.query("userId");

    const rows = await db.query.notifications.findMany({
      where: userId
        ? or(eq(schema.notifications.userId, userId), isNull(schema.notifications.userId))
        : isNull(schema.notifications.userId),
      orderBy: (n: any, { desc }: any) => [desc(n.createdAt)],
    });

    return c.json({ items: rows });
  } catch (error: any) {
    console.error("Fetch notifications error:", error.message);
    return c.json({ items: [] });
  }
});

// GET /api/v1/notifications/check
// Lightweight poll — returns only unread count + latest notification ID.
// Frontend polls this cheap endpoint and only fetches full list when count changes.
notificationsRouter.get("/check", async (c) => {
  try {
    const db = c.get("db");
    const userId = c.req.query("userId");

    const whereFilter = userId
      ? or(eq(schema.notifications.userId, userId), isNull(schema.notifications.userId))
      : isNull(schema.notifications.userId);

    const [unreadResult] = await db
      .select({ value: count() })
      .from(schema.notifications)
      .where(and(whereFilter, eq(schema.notifications.isRead, 0)));

    const latest = await db.query.notifications.findFirst({
      where: whereFilter,
      orderBy: (n: any, { desc }: any) => [desc(n.createdAt)],
      columns: { id: true, createdAt: true },
    });

    return c.json({
      unreadCount: unreadResult?.value ?? 0,
      latestId: latest?.id ?? null,
      latestAt: latest?.createdAt ?? null,
    });
  } catch (error: any) {
    console.error("Check notifications error:", error.message);
    return c.json({ unreadCount: 0, latestId: null, latestAt: null });
  }
});

// POST /api/v1/notifications
// Creates or broadcasts a notification (Admin only or system)
notificationsRouter.post("/", async (c) => {
  try {
    const db = c.get("db");
    const body = await c.req.json().catch(() => null);

    if (!body?.title || !body?.message) {
      throw new Error("VAL: Title and message are required.");
    }

    const id = crypto.randomUUID();
    await db.insert(schema.notifications).values({
      id,
      userId: body.userId || null,
      title: body.title,
      message: body.message,
      type: body.type || "info",
      isRead: 0,
      createdAt: new Date().toISOString(),
    });

    return c.json({ id, message: "Notification sent successfully" }, 201);
  } catch (error: any) {
    console.error("Create notification error:", error.message);
    return c.json({ error: error.message }, 400);
  }
});

// POST /api/v1/notifications/:id/read
notificationsRouter.post("/:id/read", async (c) => {
  try {
    const id = c.req.param("id");
    const db = c.get("db");

    await db.update(schema.notifications)
      .set({ isRead: 1 })
      .where(eq(schema.notifications.id, id));

    return c.json({ message: "Notification marked as read." });
  } catch (error: any) {
    console.error("Mark read error:", error.message);
    return c.json({ error: error.message }, 400);
  }
});

// ═══ MOUNT ROUTES ════════════════════════════════════════════

// Admin
v1.route("/banners", bannersRouter);
v1.route("/categories", categoriesRouter);
v1.route("/products", productsRouter);
v1.route("/orders", ordersRouter);

// Customer
v1.route("/auth", authRouter);
v1.route("/users", usersRouter);
v1.route("/addresses", addressesRouter);
v1.route("/reviews", reviewsRouter);
v1.route("/returns", returnsRouter);
v1.route("/settings", settingsRouter);
v1.route("/coupons", couponsRouter);
v1.route("/dashboard", dashboardRouter);
v1.route("/wallet", walletRouter);
v1.route("/notifications", notificationsRouter);

app.route("/api/v1", v1);

export const onRequest = handle(app);
