/**
 * merge-api.mjs — Merges all separate API route files into a single [[route]].ts
 * Run with: node scratch/merge-api.mjs
 */
import fs from 'fs';
import path from 'path';

const ROOT = process.cwd();
const API_DIR = path.join(ROOT, 'functions', 'api');
const ROUTES_DIR = path.join(API_DIR, 'routes');
const OUTPUT = path.join(API_DIR, '[[route]].ts');

// ─── Read source files ────────────────────────────────────
const sharedSrc = fs.readFileSync(path.join(API_DIR, 'shared.ts'), 'utf8');
const rateLimiterSrc = fs.readFileSync(path.join(API_DIR, 'utils', 'rateLimiter.ts'), 'utf8');
const emailSrc = fs.readFileSync(path.join(API_DIR, 'utils', 'email.ts'), 'utf8');

// Route files in mount order
const routeFiles = [
  'banners', 'categories', 'products', 'orders',
  'auth', 'users', 'addresses', 'reviews',
  'returns', 'settings', 'coupons', 'dashboard',
  'wallet', 'notifications',
];

// ─── Helper: strip ALL import lines (including multi-line) from source ──
function stripImports(src) {
  const lines = src.split('\n');
  const filtered = [];
  let insideImport = false;
  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed.startsWith('import ')) {
      // Single-line import: import X from "Y";
      if (trimmed.includes(' from ') && (trimmed.endsWith(';') || trimmed.endsWith('";') || trimmed.endsWith("';"))) {
        continue; // skip entire line
      }
      // Multi-line import starts here: import {\n  foo,\n  bar\n} from "...";
      insideImport = true;
      continue;
    }
    if (insideImport) {
      // Check if this line closes the multi-line import
      if (trimmed.startsWith('} from ') || trimmed.includes(' from "') || trimmed.includes(" from '")) {
        insideImport = false;
        continue; // skip the closing line too
      }
      continue; // skip intermediate lines of the multi-line import
    }
    filtered.push(line);
  }
  return filtered.join('\n');
}

// ─── Build the file ───────────────────────────────────────

let out = '';

// ═══ SECTION 1: Imports ═══
out += `// ═══════════════════════════════════════════════════════════════
// PlayPen House — Consolidated API
// All routes, utilities, and middleware in a single entry point.
// Generated by merge-api.mjs on ${new Date().toISOString().slice(0, 10)}
// ═══════════════════════════════════════════════════════════════

import { Hono } from "hono";
import { handle } from "hono/cloudflare-pages";
import { cors } from "hono/cors";
import { logger } from "hono/logger";
import { createClient } from "@libsql/client/web";
import { drizzle } from "drizzle-orm/libsql";
import { eq, count, like, or, and, isNotNull, desc, asc, sql, inArray, isNull } from "drizzle-orm";
import { sign } from "hono/jwt";
import type { LibSQLDatabase } from "drizzle-orm/libsql";
import * as schema from "../../backend/server/db/schema";

`;

// ═══ SECTION 2: Types (from shared.ts) ═══
out += `// ═══ TYPES ═══════════════════════════════════════════════════

type Bindings = {
  TURSO_URL: string;
  TURSO_AUTH_TOKEN: string;
  ADMIN_API_KEY: string;
  JWT_SECRET: string;
  GOOGLE_SCRIPT_URL: string;
  GMAIL_SENDER_EMAIL: string;
  ADMIN_NOTIFICATION_EMAIL: string;
  EMAIL_WEBHOOK_SECRET: string;
};

type Variables = {
  db: LibSQLDatabase<typeof schema>;
};

`;

// ═══ SECTION 3: Helpers (from shared.ts) ═══
out += `// ═══ HELPERS ═════════════════════════════════════════════════

const formatLinks = (c: any, path: string, id?: string) => {
  const baseUrl = new URL(c.req.url).origin + "/api/v1";
  const self = id ? \`\${baseUrl}\${path}/\${id}\` : \`\${baseUrl}\${path}\`;
  return {
    self,
    collection: id ? \`\${baseUrl}\${path}\` : undefined,
  };
};

const createPaginatedResponse = (
  items: any[],
  total: number,
  page: number,
  limit: number,
  links: any
) => {
  const pages = Math.ceil(total / limit);
  return {
    items,
    pagination: {
      total,
      page,
      limit,
      pages,
      has_next: page < pages,
      has_prev: page > 1,
    },
    _links: links,
  };
};

`;

// ═══ SECTION 4: Rate Limiter ═══
out += `// ═══ RATE LIMITER ════════════════════════════════════════════

`;
// Extract rate limiter body (strip imports, keep everything else)
const rlBody = rateLimiterSrc
  .split('\n')
  .filter(l => !l.trim().startsWith('import '))
  .join('\n');
out += rlBody + '\n\n';

// ═══ SECTION 5: Email Utility ═══
out += `// ═══ EMAIL UTILITY ═══════════════════════════════════════════

`;
const emailBody = emailSrc
  .split('\n')
  .filter(l => !l.trim().startsWith('import '))
  .join('\n');
out += emailBody + '\n\n';

// ═══ SECTION 6: App Setup (from original [[route]].ts, minus route imports) ═══
out += `// ═══ APP SETUP ═══════════════════════════════════════════════

const app = new Hono<{ Bindings: Bindings; Variables: Variables }>();

app.use("*", logger());
app.use("*", cors());

// DB Middleware
app.use("*", async (c, next) => {
  const url = c.env.TURSO_URL;
  const authToken = c.env.TURSO_AUTH_TOKEN;

  if (!url || url.includes("your-db-url")) {
    if (c.req.path === "/api/health" || c.req.path === "/api/v1/health") {
      return await next();
    }
    return c.json({ 
      error: "Database Configuration Error", 
      message: "TURSO_URL is missing or using placeholder." 
    }, 503);
  }

  try {
    const client = createClient({ url, authToken });
    c.set("db", drizzle(client, { schema }));
    await next();
  } catch (error: any) {
    console.error("DB Connection Error:", error);
    return c.json({ 
      error: "Service Unavailable", 
      message: "Could not connect to the database." 
    }, 503);
  }
});

// Error Handling
app.onError((err, c) => {
  console.error("API Error:", err);
  
  if (err.message.startsWith("VAL:")) {
    return c.json({
      error: "ValidationError",
      message: err.message.replace("VAL:", "").trim(),
      timestamp: new Date().toISOString(),
      path: c.req.path
    }, 422);
  }

  if (err.message.includes("not found")) {
    return c.json({
      error: "NotFound",
      message: err.message,
      timestamp: new Date().toISOString(),
      path: c.req.path
    }, 404);
  }

  return c.json({
    error: "InternalServerError",
    message: "An unexpected error occurred.",
    details: process.env.NODE_ENV === 'development' ? err.message : undefined,
    timestamp: new Date().toISOString(),
    path: c.req.path
  }, 500);
});

// ─── HEALTH CHECK ─────────────────────────────────────────
app.get("/api/health", (c) => c.json({ status: "ok", version: "v1" }));

// ═══ V1 ROUTES ══════════════════════════════════════════════

const v1 = new Hono<{ Bindings: Bindings; Variables: Variables }>();

// Auth Middleware for V1 (Destructive operations only)
v1.use("*", async (c, next) => {
  const method = c.req.method;
  if (method === 'GET') return await next();

  const path = c.req.path;
  const publicPaths = ["/api/v1/auth/", "/api/v1/orders", "/api/v1/reviews", "/api/v1/returns", "/api/v1/addresses", "/api/v1/users/", "/api/v1/coupons/validate"];
  const isPublic = publicPaths.some(p => path.startsWith(p));
  if (isPublic) return await next();

  const authHeader = c.req.header("Authorization");
  const apiKey = c.env.ADMIN_API_KEY;

  if (!apiKey || authHeader !== \`Bearer \${apiKey}\`) {
    return c.json({ 
      error: "Unauthorized", 
      message: "Invalid or missing API key" 
    }, 401);
  }
  await next();
});

`;

// ═══ SECTION 7: All Route Handlers ═══
for (const name of routeFiles) {
  const filePath = path.join(ROUTES_DIR, `${name}.ts`);
  const src = fs.readFileSync(filePath, 'utf8');
  
  // Determine the router variable name (e.g., bannersRouter, authRouter)
  const routerMatch = src.match(/export const (\w+Router)/);
  const routerVar = routerMatch ? routerMatch[1] : `${name}Router`;

  out += `// ── ${name.toUpperCase()} ${'─'.repeat(Math.max(1, 55 - name.length))}

`;

  // Strip all imports (single-line and multi-line), keep the rest
  let body = stripImports(src);
  
  // Replace "export const" with just "const" for the router declaration
  body = body.replace(/export const /g, 'const ');
  out += body.trim() + '\n\n';
}

// ═══ SECTION 8: Mount routes + export ═══
out += `// ═══ MOUNT ROUTES ════════════════════════════════════════════

// Admin
v1.route("/banners", bannersRouter);
v1.route("/categories", categoriesRouter);
v1.route("/products", productsRouter);
v1.route("/orders", ordersRouter);

// Customer
v1.route("/auth", authRouter);
v1.route("/users", usersRouter);
v1.route("/addresses", addressesRouter);
v1.route("/reviews", reviewsRouter);
v1.route("/returns", returnsRouter);
v1.route("/settings", settingsRouter);
v1.route("/coupons", couponsRouter);
v1.route("/dashboard", dashboardRouter);
v1.route("/wallet", walletRouter);
v1.route("/notifications", notificationsRouter);

app.route("/api/v1", v1);

export const onRequest = handle(app);
`;

// ─── Write output ─────────────────────────────────────────
fs.writeFileSync(OUTPUT, out, 'utf8');
console.log(`✅ Merged API written to: ${OUTPUT}`);
console.log(`   Total lines: ${out.split('\n').length}`);
console.log(`   Total bytes: ${Buffer.byteLength(out)}`);
